import type { ExpansionSeed } from './curriculumExpansion'
import type { GrammarLevel } from './grammar'

const lesson = (
  level: GrammarLevel,
  title: string,
  objective: string,
  vocabulary: string,
  passage: string,
  question: string,
  correct: string,
  distractorOne: string,
  distractorTwo: string,
  mainIdea: string,
  otherIdeaOne: string,
  otherIdeaTwo: string,
): ExpansionSeed => ({
  level,
  title,
  objective,
  vocabulary: vocabulary.split(';').map((pair) => {
    const [italian, english] = pair.split('=')
    return { spanish: italian, english }
  }),
  passage,
  question: { prompt: question, correct, distractors: [distractorOne, distractorTwo] },
  mainIdea: { correct: mainIdea, distractors: [otherIdeaOne, otherIdeaTwo] },
})

export const expandedItalianSeeds: ExpansionSeed[] = [
  lesson('A1', 'Una visita alla vicina', 'Descrivere una breve visita e riconoscere oggetti familiari in casa.', 'la vicina=the neighbor;la porta=the door;il tè=the tea;la sedia=the chair;nel pomeriggio=in the afternoon', 'Nel pomeriggio, Elena va a trovare la vicina. La porta è aperta e le due donne parlano in cucina. Elena beve il tè e si siede su una sedia blu.', 'Che cosa beve Elena?', 'Il tè', 'Il caffè', 'L’acqua', 'Elena fa visita alla vicina e conversa con lei.', 'Elena va a fare la spesa da sola.', 'Elena prepara un lungo viaggio.'),
  lesson('A1', 'Preparare un pranzo semplice', 'Nominare cibi comuni e descrivere un pasto semplice.', 'il riso=the rice;il pomodoro=the tomato;il formaggio=the cheese;preparare=to prepare;avere fame=to be hungry', 'Luis ha fame a mezzogiorno. Prepara il riso con pomodoro e formaggio. Sua sorella mette due piatti sul tavolo e mangiano insieme.', 'Che cosa prepara Luis?', 'Riso con pomodoro e formaggio', 'Zuppa di pesce', 'Pane e frutta', 'Luis e sua sorella condividono un pranzo semplice.', 'Luis mangia al ristorante.', 'Luis compra un tavolo nuovo.'),
  lesson('A1', 'Trovare la propria aula', 'Seguire indicazioni di base in una scuola.', 'il corridoio=the hallway;l’aula=the classroom;la porta=the door;salire=to go up;accanto a=next to', 'Marta cerca l’aula quattro. Cammina nel corridoio e sale una scala. L’aula è accanto alla biblioteca, di fronte a una porta verde.', 'Dov’è l’aula quattro?', 'Accanto alla biblioteca', 'Vicino alla mensa', 'Dietro la scuola', 'Marta segue indicazioni semplici per trovare un’aula.', 'Marta insegna in biblioteca.', 'Marta lascia la scuola in anticipo.'),
  lesson('A1', 'Scegliere i vestiti per la giornata', 'Usare parole semplici sul tempo e sull’abbigliamento per fare una scelta.', 'la camicia=the shirt;le scarpe=the shoes;fa freddo=it is cold;mettersi=to put on;il cappotto=the coat', 'Oggi fa freddo, ma c’è il sole. Paolo si mette una camicia, scarpe comode e un cappotto leggero. Prima di uscire, cerca le chiavi sul tavolo.', 'Perché Paolo mette il cappotto?', 'Perché fa freddo', 'Perché piove molto', 'Perché va a dormire', 'Paolo sceglie vestiti comodi per il tempo.', 'Paolo prepara una vacanza al mare.', 'Paolo compra mobili nuovi.'),
  lesson('A1', 'Organizzare un pomeriggio di compleanno', 'Capire un invito semplice e i dettagli di una piccola festa.', 'il compleanno=the birthday;la torta=the cake;invitare=to invite;sabato=Saturday;con gli amici=with friends', 'Sofia compie gli anni sabato. Invita tre amici a casa sua alle cinque. Suo padre prepara una piccola torta e suo fratello compra il succo.', 'Quando festeggia il compleanno Sofia?', 'Sabato', 'Lunedì', 'Venerdì mattina', 'Sofia organizza una piccola festa di compleanno a casa.', 'Sofia visita una pasticceria da sola.', 'Sofia partecipa a un grande concerto scolastico.'),
  lesson('A2', 'Attraversare la città in autobus', 'Capire un breve tragitto con linea, fermata e ora di arrivo.', 'la fermata=the stop;il biglietto=the ticket;il centro=the center;la linea=line;arrivare in orario=to arrive on time', 'Nuria prende l’autobus numero otto per arrivare in centro. Compra il biglietto con un’app e scende alla terza fermata. Siccome parte in anticipo, arriva prima dell’inizio dell’appuntamento.', 'Dove scende Nuria?', 'Alla terza fermata', 'Alla prima fermata', 'Alla stazione degli autobus', 'Nuria usa una linea di autobus per arrivare in orario a un appuntamento.', 'Nuria guida fino a un’altra città.', 'Nuria perde l’appuntamento.'),
  lesson('A2', 'Spostare una visita dal dentista', 'Chiedere un nuovo appuntamento e capire gli orari disponibili.', 'l’appuntamento=the appointment;il dentista=the dentist;la mattina=the morning;cambiare=to change;essere disponibile=to be available', 'Andrés telefona alla clinica perché non può andare all’appuntamento di martedì. La receptionist propone giovedì mattina oppure venerdì alle quattro. Andrés sceglie giovedì, quando non ha lezione.', 'Quale appuntamento sceglie Andrés?', 'Giovedì mattina', 'Venerdì alle quattro', 'Martedì pomeriggio', 'Andrés sposta l’appuntamento a un orario adatto ai suoi impegni.', 'Andrés annulla tutte le visite future.', 'Andrés chiede di parlare con un insegnante.'),
  lesson('A2', 'Riportare una giacca in negozio', 'Spiegare un problema semplice e seguire la procedura di cambio.', 'la taglia=size;riportare=to return;lo scontrino=the receipt;essere larga=to be too large;il cambio=the exchange', 'Carla compra una giacca, ma la taglia è troppo grande. Torna in negozio con lo scontrino e chiede se può cambiarla. Non c’è un’altra taglia blu, così sceglie una giacca verde dello stesso prezzo.', 'Perché Carla torna in negozio?', 'La giacca è troppo grande', 'La giacca costa troppo', 'Ha perso lo scontrino', 'Carla cambia una giacca che non le va bene.', 'Carla vuole comprare un cappotto più costoso.', 'Carla chiede al negozio di chiudere prima.'),
  lesson('A2', 'Fare programmi in base al tempo', 'Collegare le previsioni del tempo a un cambiamento pratico dei programmi.', 'le previsioni=the forecast;piovere=to rain;rimandare=to postpone;l’ombrello=the umbrella;all’aperto=outdoors', 'Le previsioni annunciano pioggia per domenica, proprio quando Diego e Ana vorrebbero fare un’escursione. Decidono di rimandarla a lunedì e di visitare il museo se il tempo resta brutto. Ana mette l’ombrello nello zaino.', 'Che cosa faranno se il tempo resta brutto?', 'Visiteranno il museo', 'Faranno l’escursione sotto la pioggia', 'Prenderanno un treno per il mare', 'Gli amici adattano un programma all’aperto alle previsioni.', 'Gli amici ignorano le previsioni e annullano il museo.', 'Gli amici comprano una casa nuova.'),
  lesson('A2', 'Informarsi su un corso di quartiere', 'Trovare i dettagli pratici in un annuncio di un corso locale.', 'il laboratorio=the workshop;iscriversi=to enroll;i materiali=the materials;gratuito=free;il quartiere=the neighborhood', 'Il centro del quartiere offre un laboratorio di cucina il mercoledì pomeriggio. L’iscrizione è gratuita, ma ogni partecipante deve portare alcuni materiali. Julia si iscrive online prima di venerdì perché i posti sono limitati.', 'Quando si svolge il laboratorio di cucina?', 'Mercoledì pomeriggio', 'Venerdì sera', 'Lunedì mattina', 'Julia si iscrive a un corso locale con posti limitati.', 'Julia insegna un corso all’università.', 'Julia compra tutti i materiali per il centro.'),
  lesson('B1', 'Risolvere un problema con un cambio di treno', 'Raccontare un imprevisto di viaggio e confrontare le soluzioni disponibili.', 'il cambio=the connection;il guasto=the breakdown;chiedere un rimborso=to claim a refund;il rimborso=the refund;l’alternativa=the alternative', 'Quando il treno regionale si è guastato, Marcos ha perso il cambio per Saragozza. In stazione gli hanno spiegato che poteva chiedere il rimborso della tratta persa oppure partire due ore dopo con un altro percorso. Ha scelto la seconda possibilità perché doveva arrivare quella sera, anche se ha avvisato la famiglia del ritardo.', 'Perché Marcos sceglie il percorso alternativo più tardi?', 'Deve arrivare quella sera', 'È l’unico percorso per Saragozza', 'Il primo treno costa meno', 'Marcos confronta il rimborso con un viaggio in ritardo e decide di proseguire.', 'Marcos decide di passare la notte in stazione.', 'Marcos perde un volo internazionale.'),
  lesson('B1', 'Organizzare uno scambio nel quartiere', 'Spiegare come i vicini coordinano un evento utile alla comunità.', 'lo scambio=the exchange;contribuire=to contribute;l’annuncio=the notice;riutilizzare=to reuse;il banco=the stall', 'Il centro civico ha organizzato uno scambio di libri e piccoli elettrodomestici. Ogni residente poteva portare fino a cinque oggetti in buono stato e il gruppo ha pubblicato gli orari per evitare code. Alla fine, Lucía si è sorpresa quando alcune persone si sono offerte di riparare gli apparecchi che nessuno voleva portare via.', 'Che cosa ha sorpreso di più Lucía?', 'Alcune persone si sono offerte di riparare gli apparecchi', 'L’evento è stato spostato in biblioteca', 'Gli organizzatori hanno venduto tutti i libri', 'Lo scambio è diventato un’attività collaborativa che favorisce il riuso.', 'Il centro ha vietato ai residenti di portare oggetti.', 'Lucía ha aperto un negozio di elettronica.'),
  lesson('B1', 'Confrontare due modi per imparare', 'Confrontare l’esperienza personale con prove pratiche sull’apprendimento.', 'l’apprendimento=learning;la costanza=consistency;le prove=the rehearsals;il progresso=the progress;verificare=to verify', 'Raúl ha iniziato a studiare la chitarra con brevi video, ma faceva progressi in modo irregolare. In seguito si è unito a un gruppo settimanale: esercitarsi con altre persone lo ha aiutato a essere costante e a sentire i propri errori. I video sono rimasti utili per ripetere una tecnica precisa, anche se da soli non gli permettevano di ricevere lo stesso tipo di commenti.', 'Che cosa ha aggiunto il gruppo settimanale?', 'Esercitarsi con altre persone e ricevere commenti', 'Più tempo per guardare video senza relazione', 'La possibilità di evitare le ripetizioni', 'Raúl combina risorse individuali e pratica regolare con altre persone.', 'Raúl impara meglio interrompendo le lezioni.', 'Il gruppo sostituisce ogni tipo di esercizio.'),
  lesson('B1', 'Comunicare un cambiamento al lavoro', 'Riassumere un cambiamento lavorativo e distinguere vantaggi e difficoltà.', 'il turno=the shift;l’avviso=the notice;conciliare=to balance;l’orario=the schedule;il personale=the staff', 'L’azienda ha annunciato che il gruppo userà un orario flessibile per tre mesi. Alcune persone sperano di conciliare meglio lavoro e vita privata, mentre altre temono che le riunioni finiscano fuori dall’orario abituale. La responsabile propone di registrare le ore e di controllare i risultati alla fine della prova.', 'Quanto durerà la prova dell’orario flessibile?', 'Tre mesi', 'Una settimana', 'Un anno intero', 'Il gruppo prova un cambiamento d’orario e ne valuterà gli effetti.', 'L’azienda ha eliminato definitivamente tutte le riunioni.', 'Il personale ha rifiutato la prova prima che iniziasse.'),
  lesson('B1', 'Scegliere un evento culturale per gli ospiti', 'Scegliere un evento considerando esigenze, accessibilità e orari.', 'il biglietto=the ticket;la capienza=the capacity;il sottotitolo=the subtitle;il percorso=the route;tenere conto=to take into account', 'Un gruppo di studenti vuole accompagnare i propri ospiti a un evento culturale, ma ci sono esigenze diverse: una persona preferisce il teatro, un’altra ha bisogno dei sottotitoli e alcuni devono rientrare presto. Confrontano orari, capienza e trasporti di tre opzioni. Alla fine scelgono una visita guidata accessibile che termina vicino alla stazione.', 'Perché scelgono la visita guidata?', 'Risponde alle esigenze di accessibilità e trasporto', 'È l’evento più lungo', 'Non ha un orario di conclusione', 'Il gruppo confronta necessità pratiche prima di scegliere un’attività inclusiva.', 'Il gruppo sceglie l’evento con meno visitatori.', 'Il gruppo evita di controllare gli orari.'),
  lesson('B2', 'Valutare una proposta di mobilità sostenibile', 'Valutare vantaggi, costi e accessibilità di una proposta sui trasporti.', 'la mobilità=mobility;lo spostamento=the commute;l’infrastruttura=infrastructure;il contributo=the subsidy;la domanda=the demand', 'Una proposta comunale vuole finanziare abbonamenti ai mezzi per ridurre gli spostamenti in auto. I sostenitori citano meno traffico ed emissioni; i critici fanno notare che, senza corse più frequenti nelle zone periferiche, lo sconto favorirebbe soprattutto chi dispone già di un servizio adeguato. La misura non può essere valutata contando solo gli abbonamenti venduti: occorre osservare chi riesce a cambiare mezzo e quali investimenti servono per mantenere l’alternativa.', 'Quale limite indicano i critici?', 'Nelle zone periferiche potrebbero mancare corse frequenti', 'La proposta aumenterebbe i parcheggi', 'Lo sconto sarebbe riservato ai turisti', 'Un contributo ai trasporti richiede un servizio affidabile per raggiungere tutta la città.', 'Vendere più abbonamenti dimostra da solo l’accessibilità.', 'Per ridurre le emissioni bisogna eliminare ogni autobus.'),
  lesson('B2', 'Stabilire limiti nel lavoro da remoto', 'Capire come aspettative chiare proteggono flessibilità e tempo libero.', 'la disponibilità=availability;disconnettersi=to disconnect;l’aspettativa=the expectation;il coordinamento=coordination;il limite=the boundary', 'Il lavoro da remoto aiuta a organizzare alcune attività, ma rende meno visibile il confine tra disponibilità e riposo. Un gruppo decide di concentrare le riunioni in due fasce e di scrivere quali questioni richiedono davvero una risposta immediata. La proposta non elimina l’autonomia: vuole evitare che ogni messaggio diventi un’urgenza e che chi lavora a orari diversi debba restare sempre connesso.', 'Perché il gruppo concentra le riunioni?', 'Per proteggere la concentrazione e il tempo libero', 'Per chiedere disponibilità costante', 'Per eliminare la flessibilità individuale', 'Il gruppo stabilisce regole di comunicazione per preservare la flessibilità.', 'Il lavoro da remoto rende inutili le aspettative scritte.', 'Ogni messaggio deve ricevere una risposta immediata.'),
  lesson('B2', 'Leggere oltre un titolo sensazionale', 'Separare le prove di un articolo dall’impressione creata dal titolo.', 'il titolo=the headline;il campione=the sample;la media=the average;la tendenza=the trend;precisare=to qualify', 'Un titolo afferma che l’uso della bicicletta è raddoppiato, ma l’articolo chiarisce che il dato viene da un sondaggio in un solo quartiere durante una settimana particolarmente calda. Il risultato è interessante, ma non dimostra una tendenza annuale né rappresenta tutta la città. Per sostenere una conclusione più ampia servono serie confrontabili, un campione vario e una spiegazione del metodo usato per raccogliere le risposte.', 'Che cosa non dimostra da solo il sondaggio?', 'Una tendenza annuale in tutta la città', 'Il numero di risposte nel quartiere', 'Che il sondaggio è avvenuto con il caldo', 'Un dato sorprendente ha bisogno di contesto prima di sostenere una conclusione ampia.', 'Ogni sondaggio è inutile, indipendentemente dal metodo.', 'L’articolo dimostra che nessuno usa più la bicicletta.'),
  lesson('B2', 'Scegliere la riparazione invece della sostituzione', 'Confrontare i compromessi pratici e ambientali tra riparare e sostituire.', 'la riparazione=the repair;la durata utile=the useful life;il ricambio=the spare part;il consumo=the consumption;la garanzia=the warranty', 'Quando la lavatrice si è guastata, il negozio ha consigliato un modello nuovo che consumava meno. Una tecnica ha però spiegato che bastava cambiare un pezzo disponibile e che la riparazione avrebbe mantenuto la garanzia residua. La decisione non dipende solo dal prezzo iniziale: conviene confrontare i consumi futuri, la durata prevista, i ricambi disponibili e l’impatto di buttare un apparecchio ancora riparabile.', 'Che cosa basta fare secondo la tecnica?', 'Sostituire un pezzo disponibile', 'Comprare una lavatrice nuova', 'Annullare la garanzia', 'La scelta dovrebbe considerare riparazione, uso futuro e impatto ambientale.', 'Il prezzo iniziale più basso determina sempre la scelta migliore.', 'Gli elettrodomestici non si possono riparare.'),
  lesson('B2', 'Discutere l’uso di uno spazio pubblico', 'Costruire una posizione equilibrata su usi diversi di uno spazio condiviso.', 'l’uso condiviso=shared use;il regolamento=the ordinance;la convivenza=coexistence;l’accesso=the access;la fascia oraria=time slot', 'Il comune valuta di limitare il traffico in una piazza per ampliare i dehors e creare un’area giochi. Chi sostiene il piano spera in più attività pedonali; chi lo critica teme che lo spazio diventi scomodo per le persone anziane o per chi deve attraversarlo. Una soluzione ragionevole dovrebbe indicare orari, percorsi accessibili e modalità di verifica, invece di presentare la scelta come un semplice contrasto tra commercio e riposo.', 'Che cosa dovrebbe specificare un piano ragionevole?', 'Orari, percorsi accessibili e verifiche', 'Solo il numero dei bar', 'Un divieto permanente per i pedoni', 'Le decisioni sugli spazi pubblici devono considerare utenti diversi ed essere verificabili.', 'Residenti e commercianti hanno le stesse esigenze.', 'La piazza dovrebbe essere riservata a un solo gruppo.'),
  lesson('C1', 'Interpretare uno studio sugli alberi in città', 'Valutare la portata delle prove di uno studio e identificarne i limiti.', 'il verde urbano=tree cover;la variabile=the variable;la correlazione=the correlation;l’esposizione=the exposure;il limite=the limitation', 'Uno studio comunale collega la presenza di alberi a temperature più basse in alcune strade, ma precisa che le misurazioni sono state effettuate in una sola stagione e non hanno controllato del tutto l’orientamento degli edifici. La correlazione sostiene l’ipotesi che l’ombra migliori il comfort; non basta però ad attribuire agli alberi tutta la differenza osservata. Un confronto tra quartieri e stagioni aiuterebbe a distinguere l’effetto della vegetazione dagli altri fattori urbani.', 'Che cosa non dimostra lo studio da solo?', 'Che gli alberi spiegano tutta la differenza di temperatura', 'Che sono state misurate le temperature delle strade', 'Che lo studio indica un limite', 'I risultati sono indicativi, ma servono confronti più ampi prima di affermare una causa.', 'I ricercatori hanno dimostrato che l’ombra non ha effetto.', 'Lo studio ha misurato ogni città per dieci anni.'),
  lesson('C1', 'Conservare un archivio locale', 'Valutare come un archivio comunitario bilancia conservazione, privacy e accesso.', 'l’archivio=the archive;il consenso=the consent;la catalogazione=cataloguing;la testimonianza=the testimony;la consultazione=the consultation', 'Un quartiere ha raccolto fotografie, lettere e testimonianze per conservare la memoria di una vecchia fabbrica. Il progetto rende accessibili materiali che restavano in scatole private, ma la digitalizzazione non stabilisce da sola chi può consultarli e per quanto tempo. Il gruppo chiede il consenso per i documenti sensibili, ne registra la provenienza e permette alle famiglie di chiedere restrizioni motivate. La politica di accesso è quindi parte della conservazione, non una formalità successiva.', 'Perché il gruppo registra la provenienza e chiede il consenso?', 'Per conservare il contesto e proteggere le persone rappresentate', 'Per rendere anonimo ogni documento', 'Per impedire alle famiglie di consultare il materiale', 'Un archivio comunitario deve unire accesso e cura etica dei materiali.', 'La digitalizzazione risolve ogni questione di proprietà.', 'Conservare significa pubblicare tutto senza limiti.'),
  lesson('C1', 'Valutare una politica scolastica sulla tecnologia', 'Analizzare benefici previsti, effetti diseguali e criteri di valutazione.', 'il divario=the gap;l’attuazione=implementation;il rendimento=performance;la formazione=training;l’indicatore=the indicator', 'Una proposta scolastica assegna dispositivi a tutti gli studenti per ampliare l’accesso ai materiali digitali. La promessa è importante, ma il risultato dipenderà anche dalla connessione domestica, dalla formazione degli insegnanti e dall’assistenza tecnica. Misurare il successo contando gli apparecchi confonderebbe l’attuazione con l’apprendimento. Una valutazione solida unirebbe dati su partecipazione e progressi a interviste capaci di spiegare perché alcuni studenti incontrano ancora ostacoli.', 'Perché non basta contare i dispositivi distribuiti?', 'Misura l’attuazione, non l’apprendimento', 'Ignora quanti dispositivi sono stati consegnati', 'Dimostra che tutti hanno internet', 'Una politica tecnologica richiede misure di risultato e informazioni sugli ostacoli.', 'Distribuire dispositivi risolve automaticamente il divario digitale.', 'Le interviste non forniscono informazioni utili.'),
  lesson('C1', 'Comunicare l’incertezza nella salute pubblica', 'Distinguere l’incertezza responsabile da una comunicazione poco chiara.', 'l’incertezza=uncertainty;la raccomandazione=the recommendation;la prova=the evidence;aggiornare=to update;la cautela=caution', 'Una raccomandazione sanitaria è cambiata dopo l’arrivo di dati raccolti su un gruppo più ampio. Alcune persone hanno interpretato l’aggiornamento come prova che il consiglio precedente fosse ingannevole; altre lo hanno considerato una revisione normale. L’istituzione avrebbe potuto spiegare che cosa era noto, che cosa restava incerto e quali prove avevano motivato il cambiamento. Riconoscere i limiti può rafforzare la fiducia se ragioni e conseguenze pratiche sono comunicate con chiarezza.', 'Che cosa avrebbe reso il cambiamento più comprensibile?', 'Spiegare ciò che era noto, incerto e sostenuto da nuove prove', 'Mantenere il vecchio consiglio senza verificarlo', 'Evitare di descrivere le prove', 'Aggiornamenti trasparenti possono rendere più credibili le indicazioni che cambiano.', 'Ogni cambiamento dimostra un inganno deliberato.', 'I messaggi pubblici dovrebbero nascondere l’incertezza.'),
  lesson('C1', 'Negoziare un orario condiviso', 'Leggere una negoziazione individuando interessi, vincoli e compromessi possibili.', 'la disponibilità=availability;il vincolo=the constraint;la fascia oraria=the time slot;cedere=to yield;l’accordo=the agreement', 'Durante la negoziazione, due gruppi non concordano sull’orario di una riunione settimanale. Uno deve finire prima delle quattro per impegni di cura; l’altro dipende da colleghi in un fuso orario diverso. Invece di ripetere le preferenze, confrontano i vincoli e alternano due fasce, condividendo un verbale con chi non può partecipare. Il compromesso non soddisfa tutti ogni settimana, ma distribuisce il costo e prevede una revisione se cambiano le necessità.', 'Come distribuisce il costo il compromesso?', 'Alterna gli orari e condivide gli appunti', 'Obbliga un gruppo a partecipare sempre tardi', 'Annulla ogni riunione in modo permanente', 'Un accordo più equo riconosce i vincoli e può essere rivisto.', 'I gruppi risolvono il problema ignorando il fuso orario.', 'Un compromesso deve soddisfare ogni persona allo stesso modo.'),
  lesson('C2', 'Riconoscere l’ironia in uno scambio cortese', 'Dedurre l’ironia dal contesto senza interpretare alla lettera una frase cortese.', 'l’ironia=irony;la riserva=the reservation;il sottotesto=subtext;l’intonazione=intonation;dare per scontato=to take for granted', 'Quando il direttore ha annunciato che il nuovo sistema avrebbe aggiunto «appena qualche minuto» a ogni pratica, l’analista ha risposto: «Che sollievo; a noi il tempo non mancava mai». La frase sembra approvare la proposta, ma il riferimento a una difficoltà nota ne capovolge il senso letterale. Tuttavia, l’ironia non si deduce da una frase isolata: il rapporto tra gli interlocutori, l’intonazione e le lamentele precedenti aiutano a distinguere una critica da uno scherzo condiviso o da un’osservazione sincera.', 'Perché la risposta dell’analista è probabilmente ironica?', 'Contrasta il risparmio di tempo promesso con una nota mancanza di tempo', 'Dichiara esplicitamente che il sistema è eccellente', 'Il direttore le chiede di calcolare i minuti', 'Il contesto può capovolgere il significato letterale di una frase cortese.', 'Ogni risposta cortese dovrebbe essere interpretata come sarcasmo.', 'Nello scambio non c’è alcuna critica.'),
  lesson('C2', 'Sintetizzare prove discordanti su una politica', 'Sintetizzare prove diverse mantenendo chiaro ciò che possono dimostrare.', 'la sintesi=synthesis;l’inferenza=the inference;la distorsione=the bias;il monitoraggio=the follow-up;il nesso causale=causality', 'Due valutazioni di un programma di formazione offrono risultati diversi. La prima registra un miglioramento immediato tra chi ha terminato il corso; la seconda, con un monitoraggio più lungo, non rileva differenze chiare nell’occupazione. I risultati non sono per forza incompatibili: cambiano popolazione, durata ed esito misurato. Una sintesi prudente riconosce il possibile beneficio formativo senza trasformarlo in una promessa di lavoro e propone un confronto tra gruppi equivalenti prima di attribuire un nesso causale al programma.', 'Perché le due valutazioni possono arrivare a conclusioni diverse?', 'Misurano gruppi, periodi ed esiti diversi', 'Una valuta il meteo in un altro paese', 'Misurano esattamente lo stesso risultato nello stesso modo', 'Le scelte di misurazione influenzano le prove, quindi le conclusioni devono rispettarne la portata.', 'Il risultato a breve termine garantisce un lavoro a lungo termine.', 'Risultati discordanti rendono impossibile ogni valutazione.'),
  lesson('C2', 'Leggere un finale letterario ambiguo', 'Confrontare interpretazioni plausibili di un finale e sostenerne una con indizi testuali.', 'il finale=the ending;l’ambiguità=ambiguity;l’indizio=the clue;l’interpretazione=the interpretation;l’omissione=the omission', 'Alla fine del racconto, Inés lascia la chiave sul tavolo ed esce senza chiudere la porta. Il narratore non spiega se pensa di tornare né se qualcuno la seguirà; dice soltanto che, per la prima volta, non guarda verso la finestra. Una lettura vede un addio, un’altra un invito a ritornare. La seconda è possibile, ma il cambiamento dello sguardo suggerisce una rottura. Ogni interpretazione dipende dal modo in cui collega quel dettaglio alle omissioni precedenti, non dalla certezza inventata per riempire il silenzio.', 'Quale dettaglio suggerisce con più forza una rottura con il passato?', 'Inés non guarda verso la finestra', 'La chiave è di metallo', 'Il tavolo è nella stanza', 'Il finale permette letture diverse, da fondare su dettagli del testo.', 'Il narratore conferma che Inés torna il giorno dopo.', 'Il racconto offre un’unica interpretazione esplicita.'),
  lesson('C2', 'Riformulare una trattativa difficile', 'Capire come la riformulazione separa le posizioni dagli interessi sottostanti.', 'la posizione=the position;l’interesse=the interest;la concessione=the concession;il margine=the room;la riformulazione=the reframing', 'Il sindacato chiede di ridurre l’orario; la direzione risponde che il bilancio impedisce qualsiasi cambiamento. Se entrambe le parti considerano definitive queste posizioni, la conversazione si blocca. Chiedendo quale problema ogni richiesta cerchi di risolvere, emergono interessi più concreti: prevedibilità per il personale e continuità del servizio per l’organizzazione. Una prova limitata, con criteri condivisi e una data di revisione, non garantisce l’accordo, ma permette di verificare un’alternativa senza presentare una concessione provvisoria come rinuncia permanente.', 'Che cosa aiuta a superare le posizioni iniziali?', 'Chiedere quale problema cerca di risolvere ogni richiesta', 'Ripetere ogni richiesta con più forza', 'Trattare una prova come una rinuncia permanente', 'Riformulare può rivelare gli interessi e creare un compromesso verificabile.', 'Le parti devono abbandonare ogni obiettivo prima di parlare.', 'Una prova temporanea garantisce l’accordo completo.'),
  lesson('C2', 'Distinguere prove e aneddoti persuasivi', 'Valutare come un aneddoto contribuisce alle prove senza sostituire un’analisi sistematica.', 'l’aneddoto=the anecdote;la rappresentatività=representativeness;la generalizzazione=the generalization;la testimonianza=the testimony;la conferma=corroboration', 'Una residente racconta che una nuova linea di autobus le ha permesso di mantenere il lavoro dopo un trasloco. La testimonianza mostra un effetto umano che una media può nascondere; da sola, però, non dimostra che il servizio avvantaggi allo stesso modo tutti i quartieri. Per decidere se estenderlo, occorre unire storie come la sua a dati su frequenza, accesso e utilizzo, cercando anche chi resta escluso. Scartare l’aneddoto perché non è statistico impoverisce la valutazione; generalizzarlo la distorce altrettanto.', 'Che cosa può mostrare più direttamente la testimonianza della residente?', 'Un effetto concreto sulla vita di una persona', 'Che ogni quartiere ha lo stesso servizio', 'Il numero medio di passeggeri della città', 'Le testimonianze e i dati sistematici rispondono a domande collegate ma diverse.', 'Una sola storia sostituisce ogni altra prova.', 'Gli aneddoti non hanno valore nella valutazione.'),
]
