import type { ExpansionSeed } from './curriculumExpansion'
import type { GrammarLevel } from './grammar'

const lesson = (
  level: GrammarLevel,
  title: string,
  objective: string,
  vocabulary: string,
  passage: string,
  question: string,
  correct: string,
  distractorOne: string,
  distractorTwo: string,
  mainIdea: string,
  otherIdeaOne: string,
  otherIdeaTwo: string,
): ExpansionSeed => ({
  level,
  title,
  objective,
  vocabulary: vocabulary.split(';').map((pair) => {
    const [spanish, english] = pair.split('=')
    return { spanish, english }
  }),
  passage,
  question: { prompt: question, correct, distractors: [distractorOne, distractorTwo] },
  mainIdea: { correct: mainIdea, distractors: [otherIdeaOne, otherIdeaTwo] },
})

export const expandedSpanishSeeds: ExpansionSeed[] = [
  lesson('A1', 'A visit to a neighbor', 'Describe a short visit and identify familiar household objects.', 'la vecina=the neighbor;la puerta=the door;el té=the tea;la silla=the chair;por la tarde=in the afternoon', 'Por la tarde, Elena visita a su vecina. La puerta está abierta y las dos hablan en la cocina. Elena toma té y se sienta en una silla azul.', 'What does Elena drink?', 'Tea', 'Coffee', 'Water', 'Elena visits her neighbor for a friendly conversation.', 'Elena goes shopping alone.', 'Elena prepares for a long trip.'),
  lesson('A1', 'Prepare a simple lunch', 'Name common foods and describe a simple meal.', 'el arroz=the rice;el tomate=the tomato;el queso=the cheese;preparar=to prepare;tener hambre=to be hungry', 'Luis tiene hambre al mediodía. Prepara arroz con tomate y queso. Su hermana pone dos platos en la mesa y ellos comen juntos.', 'What does Luis prepare?', 'Rice with tomato and cheese', 'Soup with fish', 'Bread with fruit', 'Luis and his sister share an easy lunch.', 'Luis eats at a restaurant.', 'Luis buys a new table.'),
  lesson('A1', 'Find your classroom', 'Follow basic directions around a school building.', 'el pasillo=the hallway;el aula=the classroom;la puerta=the door;subir=to go up;al lado de=next to', 'Marta busca el aula cuatro. Camina por el pasillo y sube una escalera. El aula está al lado de la biblioteca, frente a una puerta verde.', 'Where is classroom four?', 'Next to the library', 'Beside the cafeteria', 'Behind the school', 'Marta follows simple directions to find a classroom.', 'Marta teaches a class in the library.', 'Marta leaves the school early.'),
  lesson('A1', 'Choose clothes for the day', 'Use basic clothing and weather words to make a simple choice.', 'la camisa=the shirt;los zapatos=the shoes;hace frío=it is cold;ponerse=to put on;el abrigo=the coat', 'Hoy hace frío, pero hay sol. Pablo se pone una camisa, zapatos cómodos y un abrigo ligero. Antes de salir, busca las llaves en la mesa.', 'Why does Pablo put on a coat?', 'Because it is cold', 'Because it is raining heavily', 'Because he is going to sleep', 'Pablo chooses comfortable clothes for the weather.', 'Pablo is packing for a beach holiday.', 'Pablo is buying new furniture.'),
  lesson('A1', 'Plan a birthday afternoon', 'Understand a simple invitation and details about a small celebration.', 'el cumpleaños=the birthday;la tarta=the cake;invitar=to invite;el sábado=Saturday;con amigos=with friends', 'Sofía cumple años el sábado. Invita a tres amigos a su casa a las cinco. Su padre prepara una tarta pequeña y su hermano compra zumo.', 'When does Sofía celebrate her birthday?', 'On Saturday', 'On Monday', 'On Friday morning', 'Sofía plans a small birthday gathering at home.', 'Sofía visits a bakery alone.', 'Sofía has a large school concert.'),
  lesson('A2', 'Take the bus across town', 'Understand a short journey with a route, stop, and arrival time.', 'la parada=the stop;el billete=the ticket;el centro=the center;la línea=line; llegar a tiempo=to arrive on time', 'Nuria toma el autobús número ocho para llegar al centro. Compra el billete con una aplicación y baja en la tercera parada. Como sale con tiempo, llega antes de que empiece la cita.', 'Where does Nuria get off?', 'At the third stop', 'At the first stop', 'At the bus station', 'Nuria uses a bus route to reach an appointment on time.', 'Nuria drives to another city.', 'Nuria misses the appointment.'),
  lesson('A2', 'Reschedule a dentist appointment', 'Ask for a new appointment and understand available times.', 'la cita=the appointment;el dentista=the dentist;la mañana=the morning;cambiar=to change;estar disponible=to be available', 'Andrés llama a la clínica porque no puede ir a su cita del martes. La recepcionista ofrece el jueves por la mañana o el viernes a las cuatro. Andrés elige el jueves, cuando no tiene clase.', 'Which appointment does Andrés choose?', 'Thursday morning', 'Friday at four', 'Tuesday afternoon', 'Andrés changes his appointment to a time that fits his schedule.', 'Andrés cancels all future visits.', 'Andrés asks to speak with a teacher.'),
  lesson('A2', 'Return a jacket to a shop', 'Explain a simple shopping problem and follow the return process.', 'la talla=size;devolver=to return;el recibo=the receipt;quedar grande=to be too large;el cambio=the exchange', 'Carla compra una chaqueta, pero la talla le queda grande. Vuelve a la tienda con el recibo y pregunta si puede cambiarla. No hay otra talla en azul, así que elige una chaqueta verde del mismo precio.', 'Why does Carla return to the shop?', 'The jacket is too large', 'The jacket is too expensive', 'She lost the receipt', 'Carla exchanges an unsuitable jacket for one that fits.', 'Carla wants to buy a more expensive coat.', 'Carla asks the shop to close early.'),
  lesson('A2', 'Make plans around the weather', 'Combine a forecast with a practical change of plans.', 'la previsión=the forecast;llover=to rain;aplazar=to postpone;el paraguas=the umbrella;al aire libre=outdoors', 'La previsión anuncia lluvia para el domingo, justo cuando Diego y Ana querían hacer una excursión. Deciden aplazarla hasta el lunes y visitar el museo si el tiempo sigue igual. Ana guarda el paraguas en su mochila.', 'What do they plan to do if the weather stays rainy?', 'Visit the museum', 'Go hiking in the rain', 'Take a train to the beach', 'The friends adjust their outdoor plan to match the forecast.', 'The friends ignore the forecast and cancel the museum.', 'The friends plan to buy a new house.'),
  lesson('A2', 'Ask about a neighborhood course', 'Find practical details in a community class announcement.', 'el taller=the workshop;inscribirse=to enroll;los materiales=the materials;gratuito=free;el barrio=the neighborhood', 'El centro del barrio ofrece un taller de cocina los miércoles por la tarde. La inscripción es gratuita, pero cada participante debe llevar algunos materiales. Julia se apunta en línea antes del viernes porque las plazas son limitadas.', 'When does the cooking workshop meet?', 'Wednesday afternoon', 'Friday evening', 'Monday morning', 'Julia enrolls in a local class with limited places.', 'Julia teaches a course at the university.', 'Julia buys all the materials for the center.'),
  lesson('B1', 'Resolve a missed train connection', 'Recount a travel disruption and compare the available solutions.', 'el transbordo=the connection;la avería=the breakdown;reclamar=to claim;el reembolso=the refund;la alternativa=the alternative', 'Cuando el tren regional se averió, Marcos perdió el transbordo hacia Zaragoza. En la estación le explicaron que podía reclamar el importe del tramo perdido o viajar dos horas más tarde por otra ruta. Eligió la segunda opción porque necesitaba llegar esa misma noche, aunque avisó a su familia del retraso.', 'Why does Marcos choose the later alternative route?', 'He needs to arrive that night', 'It is the only route to Zaragoza', 'The first train was cheaper', 'Marcos weighs a refund against a delayed journey and chooses to continue.', 'Marcos decides to spend the night at the station.', 'Marcos misses a flight to another country.'),
  lesson('B1', 'Organize a neighborhood exchange', 'Explain how neighbors coordinate a useful community event.', 'el intercambio=the exchange;aportar=to contribute;la convocatoria=the call;reutilizar=to reuse;el puesto=the stall', 'El centro cívico organizó un intercambio de libros y pequeños electrodomésticos. Cada vecino podía aportar hasta cinco objetos en buen estado, y el equipo publicó una convocatoria con horarios para evitar filas. Al final, lo que más sorprendió a Lucía fue que varias personas se ofrecieran para reparar los aparatos que nadie quería llevarse.', 'What surprised Lucía most?', 'People volunteered to repair unwanted appliances', 'The event was moved to the library', 'The organizers sold all the books', 'The exchange became a collaborative event that encouraged reuse.', 'The center prohibited residents from bringing objects.', 'Lucía organized a commercial electronics store.'),
  lesson('B1', 'Compare two ways to learn a skill', 'Compare personal experience and practical evidence about learning.', 'el aprendizaje=learning;la constancia=consistency;el ensayo=the rehearsal;el avance=the progress;comprobar=to verify', 'Raúl empezó a estudiar guitarra con vídeos cortos, pero avanzaba de forma irregular. Más tarde se unió a un grupo semanal: practicar con otras personas le ayudó a mantener la constancia y a escuchar sus errores. Los vídeos seguían siendo útiles para repetir una técnica concreta, aunque por sí solos no le daban la misma oportunidad de recibir comentarios.', 'What did the weekly group add to Raúl’s learning?', 'Practice with others and feedback', 'More time to watch unrelated videos', 'A chance to avoid repetition', 'Raúl benefits from combining independent resources with regular shared practice.', 'Raúl learns best by stopping his lessons.', 'The group replaces every kind of practice.'),
  lesson('B1', 'Report a change at work', 'Summarize a workplace change and distinguish its benefits from its difficulties.', 'el turno=the shift;el aviso=the notice;conciliar=to balance;el horario=the schedule;la plantilla=the staff', 'La empresa anunció que el equipo pasaría a un horario flexible durante tres meses. Algunas personas esperaban que el cambio facilitara la conciliación, mientras que otras temían que las reuniones se extendieran fuera del horario habitual. Para responder a ambas inquietudes, la responsable propuso registrar las horas y revisar los resultados al final del periodo de prueba.', 'How long will the flexible schedule trial last?', 'Three months', 'One week', 'A full year', 'The team is testing a schedule change and plans to evaluate its effects.', 'The company has permanently removed every meeting.', 'The staff rejected the trial before it began.'),
  lesson('B1', 'Choose a cultural event for visitors', 'Select an event using audience needs, access, and schedule information.', 'la entrada=the ticket;el aforo=the capacity;el subtítulo=the subtitle;el recorrido=the route;tener en cuenta=to take into account', 'Un grupo de estudiantes quería llevar a sus visitantes a una actividad cultural, pero había distintas necesidades: una persona prefería el teatro, otra necesitaba subtítulos y varias debían volver temprano. Compararon el horario, el aforo y el transporte de tres opciones. Finalmente eligieron una visita guiada accesible que terminaba cerca de la estación.', 'Why does the group choose the guided visit?', 'It meets access and transport needs', 'It is the longest event', 'It has no fixed ending time', 'The group compares practical needs before choosing an inclusive activity.', 'The group chooses the event with the fewest visitors.', 'The group avoids checking schedules.'),
  lesson('B2', 'Assess a proposal for greener travel', 'Evaluate a transport proposal by weighing benefits, costs, and access.', 'la movilidad=mobility;el desplazamiento=the commute;la infraestructura=infrastructure;la subvención=the subsidy;la demanda=the demand', 'Una propuesta municipal plantea subvencionar abonos de transporte para reducir los desplazamientos en coche. Sus defensores destacan la menor congestión y la reducción de emisiones; sus críticos señalan que, sin más frecuencia en las zonas periféricas, el descuento beneficiaría sobre todo a quienes ya cuentan con un servicio adecuado. La medida, por tanto, no puede evaluarse solo por el número de abonos vendidos: también habría que observar quién logra cambiar de transporte y qué inversión exige sostener esa opción.', 'What limitation do critics identify?', 'Peripheral areas may lack frequent service', 'The proposal would increase parking spaces', 'The discount applies only to tourists', 'A travel subsidy needs reliable service to benefit people across the city.', 'Selling more passes alone proves equal access.', 'Reducing emissions requires removing every bus route.'),
  lesson('B2', 'Set boundaries in remote work', 'Identify how clear expectations can protect flexibility and shared time.', 'la disponibilidad=availability;desconectar=to disconnect;la expectativa=the expectation;la coordinación=coordination;el límite=the boundary', 'El trabajo remoto permite organizar mejor algunas tareas, pero también hace menos visible el límite entre disponibilidad y descanso. Un equipo acordó concentrar las reuniones en dos franjas y dejar por escrito qué asuntos realmente requieren respuesta inmediata. La propuesta no elimina la autonomía individual; intenta evitar que cada mensaje se convierta en una urgencia y que quienes trabajan en distintos horarios carguen con una expectativa permanente de conexión.', 'What is the purpose of concentrating meetings?', 'To protect focus and off-hours', 'To require constant availability', 'To remove individual flexibility', 'The team defines shared communication norms to preserve flexibility.', 'Remote work makes written expectations unnecessary.', 'Every message should receive an immediate answer.'),
  lesson('B2', 'Read beyond a dramatic headline', 'Separate a report’s evidence from the impression created by its headline.', 'el titular=the headline;la muestra=the sample;el promedio=the average;la tendencia=the trend;matizar=to qualify', 'Un titular afirma que el uso de bicicletas se ha duplicado, aunque el artículo aclara que la cifra procede de una encuesta en un solo distrito y durante una semana especialmente cálida. El dato puede ser relevante, pero no demuestra por sí mismo una tendencia anual ni representa a toda la ciudad. Para sostener una conclusión más amplia harían falta series comparables, una muestra diversa y una explicación de cómo se recogieron las respuestas.', 'What does the reported survey not establish by itself?', 'A citywide year-long trend', 'The number of respondents in one district', 'That the survey happened during warm weather', 'A striking statistic needs context before it supports a broad conclusion.', 'Every survey is useless regardless of its design.', 'The article proves that cycling has stopped.'),
  lesson('B2', 'Choose a repair instead of replacement', 'Compare the environmental and practical trade-offs of repair and replacement.', 'la reparación=the repair;la vida útil=the useful life;el repuesto=the spare part;el consumo=the consumption;la garantía=the warranty', 'Cuando la lavadora dejó de funcionar, la tienda recomendó comprar un modelo nuevo con menor consumo. Sin embargo, una técnica explicó que bastaba con sustituir una pieza disponible y que el arreglo conservaría la garantía restante. La decisión no depende únicamente del precio inicial: conviene comparar el consumo futuro, la vida útil probable, la disponibilidad de repuestos y el impacto de desechar un aparato que todavía puede repararse.', 'What does the technician say is needed?', 'Replacement of one available part', 'A complete new appliance', 'Removal of the warranty', 'A purchase decision should weigh repair, future use, and environmental cost.', 'The cheapest initial price always determines the best option.', 'Appliances cannot be repaired once they stop working.'),
  lesson('B2', 'Discuss the use of public space', 'Build a balanced position about competing uses of a shared public area.', 'el uso compartido=shared use;la ordenanza=the ordinance;la convivencia=coexistence;el acceso=the access;la franja horaria=time slot', 'El ayuntamiento estudia limitar el tráfico en una plaza para ampliar las terrazas y crear una zona de juego. Quienes apoyan el plan esperan más actividad peatonal; quienes lo cuestionan temen que el espacio deje de ser cómodo para residentes mayores o para quienes necesitan atravesarlo. Una solución razonable tendría que especificar horarios, rutas accesibles y mecanismos de revisión, en vez de presentar la medida como una elección simple entre comercio y descanso.', 'Which elements does the passage say a reasonable plan should specify?', 'Schedules, accessible routes, and review', 'Only the number of cafés', 'A permanent ban on pedestrians', 'Public-space decisions should account for different users and be reviewable.', 'Residents and businesses have identical needs.', 'The plaza should be reserved for a single group.'),
  lesson('C1', 'Interpret a study on urban trees', 'Evaluate the scope of evidence in a study and identify its limits.', 'el arbolado=tree cover;la variable=the variable;la correlación=the correlation;la exposición=the exposure;la limitación=the limitation', 'Un estudio municipal relaciona la presencia de árboles con temperaturas más bajas en varias calles, pero advierte que las mediciones se realizaron en una sola estación y no controlaron por completo la orientación de los edificios. La correlación respalda la hipótesis de que la sombra influye en el confort térmico; no basta, sin embargo, para atribuir a los árboles toda la diferencia observada. Una comparación entre barrios y estaciones permitiría distinguir mejor el efecto de la vegetación de otros factores urbanos.', 'What does the study not prove on its own?', 'That trees explain the entire temperature difference', 'That temperatures were measured on streets', 'That the study included a limitation', 'The findings are suggestive but need broader comparison before causal claims.', 'The researchers proved that shade has no effect.', 'The study measured every city for a full decade.'),
  lesson('C1', 'Preserve a local archive', 'Consider how community archives balance preservation, privacy, and access.', 'el archivo=the archive;el consentimiento=the consent;la catalogación=cataloguing;el testimonio=the testimony;la consulta=the consultation', 'Un barrio reunió fotografías, cartas y testimonios para conservar la memoria de una antigua fábrica. La iniciativa amplía el acceso a materiales que antes permanecían en cajas privadas, aunque digitalizar no resuelve por sí solo quién puede consultarlos ni durante cuánto tiempo. El equipo acordó solicitar consentimiento para documentos sensibles, registrar su procedencia y permitir que las familias pidan restricciones justificadas. La política de acceso, por tanto, forma parte del trabajo de preservación y no es un trámite posterior.', 'Why does the team record provenance and obtain consent?', 'To preserve context and protect people represented', 'To make every document anonymous', 'To prevent families from reviewing material', 'A community archive must combine access with ethical stewardship.', 'Digitization removes all questions about ownership.', 'Preservation means publishing every item without limits.'),
  lesson('C1', 'Evaluate a school technology policy', 'Analyze a policy’s intended benefits, unequal effects, and evaluation criteria.', 'la brecha=the gap;la implementación=implementation;el rendimiento=performance;la capacitación=training;el indicador=the indicator', 'Una propuesta escolar ofrece dispositivos a todo el alumnado para ampliar el acceso a materiales digitales. Su promesa es importante, pero el resultado dependerá también de la conexión en casa, la capacitación docente y la disponibilidad de apoyo técnico. Medir el éxito solo por el número de aparatos entregados confundiría implementación con aprendizaje. Una evaluación sólida combinaría indicadores de participación y progreso con entrevistas que expliquen por qué algunos estudiantes siguen encontrando obstáculos.', 'Why is counting distributed devices an insufficient measure?', 'It measures implementation rather than learning', 'It ignores the number of devices delivered', 'It proves students have equal internet access', 'Technology policy needs outcome measures and context about remaining barriers.', 'Device distribution automatically resolves the digital divide.', 'Interviews cannot provide useful information.'),
  lesson('C1', 'Communicate uncertainty in public health', 'Distinguish responsible uncertainty from weak communication in an evolving advisory.', 'la incertidumbre=uncertainty;la recomendación=the recommendation;la evidencia=the evidence;actualizar=to update;la cautela=caution', 'Una recomendación sanitaria cambió cuando aparecieron datos de un grupo más amplio. Algunas personas interpretaron la actualización como señal de que el consejo anterior era engañoso; otras la entendieron como parte de una revisión normal. La institución habría podido explicitar qué se sabía, qué seguía incierto y qué evidencia motivó el cambio. Reconocer los límites no debilita necesariamente un mensaje: puede aumentar la confianza si las razones y las consecuencias prácticas se comunican con claridad.', 'What could have made the change easier to understand?', 'Explaining what was known, uncertain, and newly evidenced', 'Keeping the original advice without review', 'Avoiding any description of the evidence', 'Transparent updates can make changing guidance more trustworthy.', 'Any change in advice proves deliberate deception.', 'Public messages should hide uncertainty.'),
  lesson('C1', 'Negotiate a shared meeting schedule', 'Read a negotiation for its interests, constraints, and workable compromise.', 'la disponibilidad=availability;la restricción=the constraint;la franja=the time slot;ceder=to yield;el acuerdo=the agreement', 'En la negociación, dos equipos discrepan sobre la hora de una reunión semanal. Uno necesita terminar antes de las cuatro por responsabilidades de cuidado; el otro depende de colegas en otra zona horaria. En lugar de repetir preferencias, comparan las restricciones y acuerdan alternar dos franjas, con una agenda escrita para quienes no puedan asistir. El compromiso no satisface por igual cada semana, pero distribuye el coste y conserva una vía para revisar el acuerdo si cambian las necesidades.', 'How does the proposed compromise distribute the scheduling burden?', 'By alternating time slots and sharing notes', 'By requiring one team to attend every late meeting', 'By cancelling all meetings permanently', 'A fairer agreement recognizes constraints and includes a way to review it.', 'The teams resolve the disagreement by ignoring time zones.', 'A compromise must satisfy every person identically.'),
  lesson('C2', 'Trace irony in a polite exchange', 'Infer irony from context without treating a polite phrase as literal agreement.', 'la ironía=irony;la reserva=the reservation;el subtexto=subtext;la entonación=intonation;dar por hecho=to take for granted', 'Cuando el director anunció que el nuevo sistema «apenas añadiría unos minutos» a cada trámite, la analista respondió: «Qué alivio; siempre nos sobraba tiempo». La frase parece agradecer la propuesta, pero la referencia a una escasez conocida invierte su sentido literal. Aun así, la ironía no debe inferirse de una sola oración aislada: la relación entre interlocutores, la entonación y las quejas anteriores determinan si se trata de crítica, humor compartido o una observación genuina.', 'Why is the analyst’s response likely ironic?', 'It contrasts the claimed time savings with a known lack of time', 'She explicitly says the system is excellent', 'The director asks her to calculate the minutes', 'Context can reverse a polite phrase’s literal meaning.', 'Every polite response should be read as sarcasm.', 'The exchange contains no criticism.'),
  lesson('C2', 'Synthesize conflicting policy evidence', 'Synthesize mixed evidence while preserving what it can and cannot establish.', 'la síntesis=synthesis;la inferencia=the inference;el sesgo=the bias;el seguimiento=the follow-up;la causalidad=causality', 'Dos evaluaciones de un programa de formación ofrecen resultados distintos. La primera registra una mejora inmediata entre quienes terminaron el curso; la segunda, con seguimiento más largo, no encuentra diferencias claras en el empleo. No son necesariamente incompatibles: difieren en población, plazo y resultado medido. Una síntesis prudente reconoce el posible beneficio formativo sin convertirlo en una promesa laboral, y propone comparar grupos equivalentes antes de atribuir causalidad al programa.', 'Why might the two evaluations reach different conclusions?', 'They measure different groups, time periods, and outcomes', 'One evaluation studies a different country’s weather', 'Both measure exactly the same result in the same way', 'Evidence can vary with measurement choices, so conclusions should preserve scope.', 'The short-term result guarantees a long-term job.', 'Conflicting results make all evaluation impossible.'),
  lesson('C2', 'Read an ambiguous literary ending', 'Compare plausible interpretations of an ending and support one with textual clues.', 'el desenlace=the ending;la ambigüedad=ambiguity;el indicio=the clue;la interpretación=the interpretation;la omisión=the omission', 'Al final del relato, Inés deja la llave sobre la mesa y sale sin cerrar la puerta. El narrador no explica si espera volver ni si alguien la seguirá; solo menciona que, por primera vez, no mira hacia la ventana. Una lectura entiende el gesto como despedida, otra como invitación a regresar. La segunda parece posible, aunque el cambio de mirada sugiere una ruptura. La fuerza de cada interpretación depende de cómo conecte ese detalle con las omisiones previas, no de completar el silencio con una certeza inventada.', 'Which detail most strongly suggests a break with the past?', 'Inés does not look back at the window', 'The key is made of metal', 'The table is in the room', 'The ending invites competing readings that should be grounded in textual details.', 'The narrator confirms that Inés returns the next day.', 'The story provides one explicit interpretation.'),
  lesson('C2', 'Reframe a difficult negotiation', 'Identify how reframing separates positions from the interests behind them.', 'la postura=the position;el interés=the interest;la concesión=the concession;el margen=the room;la reformulación=the reframing', 'El sindicato pide reducir la jornada; la dirección responde que el presupuesto impide cualquier cambio. Si ambas partes tratan esas posiciones como definitivas, la conversación se estanca. Al preguntar qué problema intenta resolver cada petición, aparecen intereses más concretos: previsibilidad para el personal y continuidad del servicio para la organización. Una prueba limitada, con criterios acordados y una fecha de revisión, no garantiza consenso, pero permite comprobar si una alternativa atiende ambos intereses sin presentar una concesión provisional como renuncia permanente.', 'What helps move the negotiation beyond fixed positions?', 'Asking which underlying problem each request addresses', 'Repeating each demand more forcefully', 'Treating a trial as a permanent surrender', 'Reframing can uncover interests and create a testable compromise.', 'The parties must abandon every goal before talking.', 'A temporary trial guarantees full agreement.'),
  lesson('C2', 'Separate evidence from a persuasive anecdote', 'Evaluate how an anecdote contributes to, but cannot replace, systematic evidence.', 'la anécdota=the anecdote;la representatividad=representativeness;la generalización=the generalization;el testimonio=the testimony;la corroboración=corroboration', 'Una residente cuenta que una nueva ruta de autobús le permitió conservar su empleo después de mudarse. Su testimonio muestra un efecto humano que un promedio puede ocultar; no demuestra, por sí solo, que la ruta beneficie por igual a todos los barrios. Para decidir si ampliar el servicio, conviene combinar relatos como el suyo con datos de frecuencia, acceso y uso, y buscar a quienes todavía quedan fuera. Descartar la anécdota por no ser estadística empobrece la evaluación; generalizar desde ella también la distorsiona.', 'What can the resident’s anecdote show most directly?', 'A concrete effect on one person’s life', 'That every neighborhood has equal service', 'The exact average ridership for the whole city', 'Qualitative testimony and systematic data answer related but different questions.', 'One personal story replaces every other kind of evidence.', 'Anecdotes have no value in policy evaluation.'),
]
