import type { AssessmentQuestion } from './assessment'
import type { GrammarLesson, GrammarLevel } from './grammar'
import type { SupplementalLesson, StarterLesson } from './learnCourse'
import type { PracticeActivity } from './practice'
import type { Resource } from './resourceCatalog'
import { buildCollegeGrammarLessons } from './collegeCurriculum.ts'

export type AddedLanguage = 'Mandarin Chinese' | 'Modern Standard Arabic' | 'Russian'

type Phrase = { target: string; english: string; title: string }
type GrammarTopic = { title: string; summary: string; explanation: string; examples: [string, string] }
type LanguageProfile = {
  name: AddedLanguage
  code: string
  script: 'Hans' | 'Arab' | 'Cyrl'
  phrases: Record<GrammarLevel, Phrase[]>
  reading: Record<GrammarLevel, string>
  grammar: Record<GrammarLevel, [GrammarTopic, GrammarTopic]>
  starter: [string, string, string]
}

const levels: GrammarLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
const lessonMinutes: Record<GrammarLevel, number> = { A1: 12, A2: 16, B1: 20, B2: 24, C1: 28, C2: 32 }
const readingExtensions: Record<AddedLanguage, Record<GrammarLevel, string>> = {
  'Mandarin Chinese': {
    A1: '在附近的社区，大家有简单的日常活动。早上，商店开门，学生去学校，邻居互相问好。广场上有树，也有长椅。人们在那里休息、聊天，然后回家。\n\n晚上，一些家庭一起散步。孩子们在广场上玩，大人坐下来休息。离家近的公共地方可以让邻居见面，也可以让人们认识自己的社区。',
    A2: '城市里的图书馆不只是借书的地方。早上，有人看报纸，有人准备考试；下午，孩子们做作业，家庭参加免费的活动。工作人员也帮助读者寻找资料和使用电脑。\n\n但是，并不是每个人都能方便地去图书馆。有些居民住得很远，另一些人工作到很晚。因此，市政府正在考虑延长开放时间，并在不同社区安排活动。在改变服务以前，工作人员希望先了解居民的需要。',
    B1: '一些居民建议改善市场旁边的广场。讨论时，有人希望增加树木和长椅，也有人指出人行道太窄，老人和推婴儿车的人不容易通过。市政府听取了这些意见，设计了一个新方案：保留商店门口的通道，并在不影响行人的地方种树。\n\n第一阶段只是试行，为期三个月。工作人员会观察广场的使用情况，也会询问居民、商店经营者和来访者。试行结束以后，大家会比较实际情况和最初的计划。如果某些变化没有达到目的，设计还可以调整。',
    B2: '新的公共交通方案希望减少堵车和通勤时间。增加班次可能缩短等候时间，但公交车还需要方便地连接火车，也需要服务目前交通不便的社区。只增加车辆，并不能保证每个人都能顺利完成行程。\n\n计划也需要长期资金。购买车辆、雇用司机和维护设备都会产生费用，施工期间还可能影响现有路线。市政府应当公布评估标准，比较不同地区的结果，并听取依靠公共交通出行的人提出的意见。先进行小范围试行，有助于在全面实施以前发现没有预料到的问题。',
    C1: '市政府的报告发现，增加公交班次以后，平均等候时间有所下降。不过，研究只持续了几个星期，比较的社区条件也不相同，而且没有排除所有影响准点率的因素。因此，观察到两项变化同时发生，并不能证明增加班次是唯一原因。\n\n平均数也可能掩盖不同乘客的实际经历。中心城区的数据改善时，郊区路线或夜间乘客的等候时间仍可能很长。报告建议延长观察时间，并按路线、时段和换乘情况分别分析数据。更完整的评估还应结合访谈，解释研究的局限，并说明结论适用于哪些地区。',
    C2: '委员会没有否定改革本身，而是质疑现有方案能否在不把成本转移给其他群体的情况下实现目标。初步指标显示平均行车速度提高了，但这并不能说明换乘是否更加可靠，也没有反映中心城区与外围社区之间的差异。部分改善还可能与早已安排的时刻表调整有关。\n\n因此，同一组结果可以支持不同解释：投资可能带来了真实收益，也可能只是使部分路线受益，或者与测量方式有关。委员会要求在更长时期内收集可比较的数据，并分析不同班次对工作人员和乘客的影响。在证据更加充分以前，可以确认的只是部分行程有所改善；整个系统是否更加公平、稳定，还不能确定。',
  },
  'Modern Standard Arabic': {
    A1: 'فِي الْحَيِّ أَنْشِطَةٌ يَوْمِيَّةٌ بَسِيطَةٌ. فِي الصَّبَاحِ يَفْتَحُ الْمَتْجَرُ أَبْوَابَهُ، وَيَذْهَبُ الطُّلَّابُ إِلَى الْمَدْرَسَةِ، وَيُحَيِّي الْجِيرَانُ بَعْضُهُمْ بَعْضًا. فِي السَّاحَةِ أَشْجَارٌ وَمَقَاعِدُ. يَجْلِسُ النَّاسُ هُنَاكَ وَيَتَحَدَّثُونَ قَلِيلًا.\n\nفِي الْمَسَاءِ تَتَنَزَّهُ بَعْضُ الأُسَرِ مَعًا. يَلْعَبُ الأَطْفَالُ، وَيَسْتَرِيحُ الْكِبَارُ. يُسَاعِدُ الْمَكَانُ الْقَرِيبُ مِنَ الْبَيْتِ عَلَى لِقَاءِ الْجِيرَانِ وَالتَّعَرُّفِ إِلَى الْحَيِّ.',
    A2: 'لَا تُقَدِّمُ الْمَكْتَبَةُ فِي الْمَدِينَةِ الْكُتُبَ فَقَطْ. فِي الصَّبَاحِ يَقْرَأُ بَعْضُ النَّاسِ الصَّحِيفَةَ وَيَسْتَعِدُّ آخَرُونَ لِامْتِحَانٍ. وَفِي الْمَسَاءِ يُنْجِزُ الأَطْفَالُ وَاجِبَاتِهِمْ وَتُشَارِكُ الأُسَرُ فِي أَنْشِطَةٍ مَجَّانِيَّةٍ. كَمَا يُسَاعِدُ الْمُوَظَّفُونَ الزُّوَّارَ عَلَى الْبَحْثِ عَنِ الْمَعْلُومَاتِ وَاسْتِخْدَامِ الْحَوَاسِيبِ.\n\nوَلَكِنَّ الذَّهَابَ إِلَى الْمَكْتَبَةِ لَيْسَ سَهْلًا لِلْجَمِيعِ. فَبَعْضُ السُّكَّانِ يَعِيشُونَ بَعِيدًا، وَيَعْمَلُ آخَرُونَ فِي أَوْقَاتِ فَتْحِهَا. لِذَلِكَ تَدْرُسُ الْبَلَدِيَّةُ إِمْكَانِيَّةَ تَمْدِيدِ سَاعَاتِ الْعَمَلِ وَتَنْظِيمِ أَنْشِطَةٍ فِي أَحْيَاءَ مُخْتَلِفَةٍ. وَقَبْلَ تَغْيِيرِ الْخِدْمَةِ، تُرِيدُ مَعْرِفَةَ احْتِيَاجَاتِ السُّكَّانِ.',
    B1: 'اقْتَرَحَ مَجْمُوعَةٌ مِنَ السُّكَّانِ تَحْسِينَ السَّاحَةِ الْقَرِيبَةِ مِنَ السُّوقِ. طَلَبَ بَعْضُهُمْ زِيَادَةَ الأَشْجَارِ وَالْمَقَاعِدِ، فِي حِينِ أَشَارَ آخَرُونَ إِلَى أَنَّ الأَرْصِفَةَ الضَّيِّقَةَ تُصَعِّبُ الْمَرُورَ عَلَى كِبَارِ السِّنِّ وَالأُسَرِ مَعَ عَرَبَاتِ الأَطْفَالِ. جَمَعَتِ الْبَلَدِيَّةُ الآرَاءَ وَأَعَدَّتْ تَصْمِيمًا يُبْقِي مَدَاخِلَ الْمَتَاجِرِ مَفْتُوحَةً وَيَزْرَعُ الأَشْجَارَ فِي أَمَاكِنَ لَا تَعُوقُ الْمَارَّةَ.\n\nسَتَكُونُ الْمَرْحَلَةُ الأُولَى تَجْرِبَةً مُؤَقَّتَةً لِثَلَاثَةِ أَشْهُرٍ. سَيُرَاقِبُ الْمُوَظَّفُونَ اسْتِخْدَامَ السَّاحَةِ وَيَسْأَلُونَ السُّكَّانَ وَأَصْحَابَ الْمَتَاجِرِ وَالزُّوَّارَ عَنْ تَجْرِبَتِهِمْ. بَعْدَ ذَلِكَ سَيُقَارِنُونَ النَّتَائِجَ بِالتَّوَقُّعَاتِ الأُولَى، وَيُعَدِّلُونَ التَّصْمِيمَ إِذَا ظَهَرَتْ مُشْكِلَاتٌ جَدِيدَةٌ.',
    B2: 'تَهْدِفُ خُطَّةُ النَّقْلِ الْعَامِّ الْجَدِيدَةُ إِلَى تَقْلِيلِ الِازْدِحَامِ وَوَقْتِ التَّنَقُّلِ. وَقَدْ يُسَاعِدُ تَكْثِيفُ الرَّحَلَاتِ عَلَى تَقْلِيلِ الِانْتِظَارِ، لَكِنَّ ذَلِكَ يَتَوَقَّفُ عَلَى جَوْدَةِ الرَّبْطِ بِالْقِطَارَاتِ وَوُصُولِ الْخِدْمَةِ إِلَى الأَحْيَاءِ الأَقَلِّ خِدْمَةً. فَزِيَادَةُ عَدَدِ الْحَافِلَاتِ وَحْدَهَا لَا تَضْمَنُ وُصُولَ كُلِّ رَاكِبٍ إِلَى وِجْهَتِهِ.\n\nوَتَحْتَاجُ الْخُطَّةُ أَيْضًا إِلَى تَمْوِيلٍ مُسْتَقِرٍّ. فَشِرَاءُ الْمَرْكَبَاتِ وَتَوْظِيفُ السَّائِقِينَ وَصِيَانَةُ الْمَعَدَّاتِ تَتَطَلَّبُ نَفَقَاتٍ مُسْتَمِرَّةً، وَقَدْ تُؤَثِّرُ أَعْمَالُ الْبِنَاءِ فِي الْمَسَارَاتِ الْحَالِيَّةِ مُؤَقَّتًا. وَيَنْبَغِي لِلْبَلَدِيَّةِ أَنْ تُعْلِنَ مَعَايِيرَ التَّقْيِيمِ وَتُقَارِنَ النَّتَائِجَ بَيْنَ الأَحْيَاءِ وَتَسْتَمِعَ إِلَى الْمُسْتَخْدِمِينَ. وَقَدْ تُسَاعِدُ تَجْرِبَةٌ مَحْدُودَةٌ عَلَى اكْتِشَافِ آثَارٍ غَيْرِ مُتَوَقَّعَةٍ قَبْلَ تَعْمِيمِ التَّغْيِيرِ.',
    C1: 'يَرْبِطُ تَقْرِيرُ الْبَلَدِيَّةِ بَيْنَ زِيَادَةِ عَدَدِ رَحَلَاتِ الْحَافِلَاتِ وَانْخِفَاضِ مُتَوَسِّطِ وَقْتِ الِانْتِظَارِ. غَيْرَ أَنَّ النَّتَائِجَ تَحْتَاجُ إِلَى قِرَاءَةٍ حَذِرَةٍ؛ فَالدِّرَاسَةُ لَمْ تَسْتَمِرَّ إِلَّا أَسَابِيعَ قَلِيلَةً، وَقَارَنَتْ بَيْنَ أَحْيَاءٍ مُخْتَلِفَةٍ، وَلَمْ تَعْزِلْ جَمِيعَ الْعَوَامِلِ الَّتِي تُؤَثِّرُ فِي مَوَاعِيدِ الْوُصُولِ. وَلَا يُثْبِتُ حُدُوثُ تَغَيُّرَيْنِ فِي الْوَقْتِ نَفْسِهِ أَنَّ أَحَدَهُمَا السَّبَبُ الْوَحِيدُ لِلآخَرِ.\n\nوَقَدْ يُخْفِي الْمُتَوَسِّطُ فُرُوقًا مُهِمَّةً فِي تَجْرِبَةِ الرُّكَّابِ. فَقَدْ تَتَحَسَّنُ الأَرْقَامُ فِي وَسَطِ الْمَدِينَةِ، بَيْنَمَا يَطُولُ انْتِظَارُ رُكَّابِ الْأَحْيَاءِ الْبَعِيدَةِ أَوْ رُكَّابِ اللَّيْلِ. وَيُوصِي مُعِدُّو التَّقْرِيرِ بِتَمْدِيدِ فَتْرَةِ الْمُرَاقَبَةِ وَتَحْلِيلِ الْبَيَانَاتِ حَسَبَ الْمَسَارِ وَالْوَقْتِ وَنَوْعِ الرَّبْطِ. وَيَنْبَغِي أَنْ تَجْمَعَ الدِّرَاسَةُ بَيْنَ الأَرْقَامِ وَالْمُقَابَلَاتِ، وَأَنْ تُوَضِّحَ حُدُودَ النَّتَائِجِ وَالظُّرُوفَ الَّتِي تَنْطَبِقُ عَلَيْهَا.',
    C2: 'لَمْ تَرْفُضِ اللَّجْنَةُ الإِصْلَاحَ، بَلْ تَسَاءَلَتْ عَمَّا إِذَا كَانَتِ الْخُطَّةُ الْحَالِيَّةُ قَادِرَةً عَلَى تَحْقِيقِ أَهْدَافِهَا مِنْ دُونِ نَقْلِ التَّكَالِيفِ إِلَى فِئَاتٍ أُخْرَى. تُظْهِرُ الْمُؤَشِّرَاتُ الأُولَى زِيَادَةً فِي مُتَوَسِّطِ السُّرْعَةِ، لَكِنَّ هَذَا الرَّقْمَ لَا يَقِيسُ وَحْدَهُ مَوْثُوقِيَّةَ التَّحْوِيلَاتِ بَيْنَ الْخُطُوطِ، وَلَا يُبَيِّنُ الْفَرْقَ بَيْنَ وَسَطِ الْمَدِينَةِ وَأَطْرَافِهَا. وَقَدْ يَرْجِعُ جُزْءٌ مِنَ التَّحَسُّنِ إِلَى تَعْدِيلَاتٍ فِي الْجَدَاوِلِ كَانَتْ مُقَرَّرَةً مِنْ قَبْلُ.\n\nوَلِذَلِكَ تَحْتَمِلُ النَّتَائِجُ أَكْثَرَ مِنْ تَفْسِيرٍ. فَقَدْ تَكُونُ الِاسْتِثْمَارَاتُ قَدْ حَقَّقَتْ مَنْفَعَةً حَقِيقِيَّةً، أَوْ تَكُونُ ظُرُوفُ الْقِيَاسِ قَدْ أَفَادَتْ بَعْضَ الْمَسَارَاتِ عَلَى حِسَابِ غَيْرِهَا. وَتَطْلُبُ اللَّجْنَةُ بَيَانَاتٍ قَابِلَةً لِلْمُقَارَنَةِ عَلَى فَتْرَةٍ أَطْوَلَ، إِلَى جَانِبِ تَقْيِيمِ أَثَرِ الْخُطَّةِ فِي الْمُوَظَّفِينَ وَالرُّكَّابِ ذَوِي الْجَدَاوِلِ الأَقَلِّ مُرُونَةً. وَحَتَّى تَكْتَمِلَ الأَدِلَّةُ، يَبْقَى الِاسْتِنْتَاجُ الأَدَقُّ مَحْدُودًا: تَحَسَّنَتْ بَعْضُ الرِّحْلَاتِ، وَلَكِنْ لَمْ يَثْبُتْ بَعْدُ أَنَّ النِّظَامَ كُلَّهُ أَكْثَرُ عَدْلًا أَوِ اسْتِقْرَارًا.',
  },
  Russian: {
    A1: 'В районе у людей есть простые повседневные дела. Утром открывается магазин, ученики идут в школу, а соседи здороваются. На площади растут деревья и стоят скамейки. Люди отдыхают там и немного разговаривают.\n\nВечером некоторые семьи гуляют вместе. Дети играют, а взрослые отдыхают. Место рядом с домом помогает соседям встречаться и лучше узнавать свой район.',
    A2: 'Городская библиотека предлагает не только книги. Утром одни посетители читают газеты, а другие готовятся к экзаменам. После обеда дети делают уроки, а семьи приходят на бесплатные занятия. Сотрудники помогают найти информацию и пользоваться компьютерами.\n\nОднако не всем удобно добираться до библиотеки. Некоторые жители живут далеко, а другие работают в часы её работы. Поэтому город рассматривает возможность продлить часы и проводить занятия в разных районах. Прежде чем менять услугу, сотрудники хотят узнать, что нужно жителям.',
    B1: 'Жители предложили благоустроить площадь возле рынка. На встречах одни просили посадить деревья и поставить скамейки, другие обращали внимание на узкие тротуары, по которым трудно проходить пожилым людям и родителям с колясками. Город собрал мнения и подготовил проект: входы в магазины останутся свободными, а деревья появятся там, где они не мешают движению.\n\nСначала изменения будут временными: пробный этап продлится три месяца. Сотрудники будут наблюдать за площадью и спрашивать жителей, владельцев магазинов и посетителей об их опыте. Затем они сравнят результаты с первоначальными ожиданиями. Если появятся новые трудности, проект можно будет изменить.',
    B2: 'Новый план общественного транспорта призван уменьшить пробки и время поездок. Более частые рейсы могут сократить ожидание, однако их польза зависит от удобных пересадок на поезда и обслуживания районов, где сейчас мало маршрутов. Само по себе увеличение числа автобусов не гарантирует, что пассажиры смогут завершить поездку.\n\nПлану требуется устойчивое финансирование. Покупка транспорта, найм водителей и обслуживание оборудования связаны с постоянными расходами, а строительные работы могут временно изменить привычные маршруты. Городским властям следует заранее опубликовать критерии оценки, сравнить результаты в разных районах и выслушать пассажиров. Ограниченный пробный этап поможет обнаружить неожиданные последствия до масштабного внедрения.',
    C1: 'В отчёте города увеличение числа автобусных рейсов связывается со снижением среднего времени ожидания. Однако выводы следует толковать осторожно: исследование продолжалось всего несколько недель, сравнивались районы с разными условиями, а все факторы, влияющие на пунктуальность, учтены не были. Одновременное изменение двух показателей само по себе не доказывает, что одно стало единственной причиной другого.\n\nСреднее значение также может скрывать различия в опыте пассажиров. Показатели в центре могут улучшиться, хотя на окраинных маршрутах или вечером ожидание останется долгим. Авторы предлагают продлить наблюдение и отдельно анализировать данные по маршрутам, времени суток и пересадкам. Более полная оценка должна сочетать статистику с интервью, обозначать ограничения исследования и уточнять, к каким условиям применимы выводы.',
    C2: 'Комиссия не выступила против реформы, но усомнилась, позволит ли нынешний проект достичь заявленных целей, не переложив расходы на другие группы. Первые показатели свидетельствуют о росте средней скорости, однако сами по себе они не отражают надёжность пересадок и различия между центром и окраинами. Кроме того, часть улучшения может совпасть с изменениями расписания, запланированными заранее.\n\nСледовательно, результаты допускают несколько объяснений. Инвестиции могли принести реальную пользу, но измерение могло оказаться более благоприятным для одних маршрутов, чем для других. Комиссия просит собрать сопоставимые данные за более длительный период и оценить последствия для работников и пассажиров с менее гибким расписанием. Пока обоснован лишь ограниченный вывод: некоторые поездки стали лучше, но общая справедливость и устойчивость системы ещё не доказаны.',
  },
}

export function getLanguageReadingExtension(language: AddedLanguage, level: GrammarLevel) {
  return readingExtensions[language][level]
}

const dlptQuestions: Record<GrammarLevel, Array<{ prompt: string; answers: string[]; correctIndex: number }>> = {
  A1: [
    { prompt: 'Main idea · What is the passage mainly about?', answers: ['A learner’s daily language-study routine.', 'A family planning a long trip.', 'A school changing its schedule.', 'A shop preparing for a holiday.'], correctIndex: 0 },
    { prompt: 'Detail · How does the learner respond when a friend asks a question?', answers: ['The learner answers slowly.', 'The learner changes the subject.', 'The learner writes a long report.', 'The learner leaves the community.'], correctIndex: 0 },
    { prompt: 'Sequence · When will the learner review again?', answers: ['Tomorrow.', 'Last week.', 'Before going to school yesterday.', 'Only during the evening walk.'], correctIndex: 0 },
    { prompt: 'Inference · What can be inferred about the learner?', answers: ['The learner practises regularly and is still building confidence.', 'The learner has stopped studying.', 'The learner already understands every conversation.', 'The learner studies only when travelling.'], correctIndex: 0 },
  ],
  A2: [
    { prompt: 'Main idea · What is the passage mainly about?', answers: ['A trip to a nearby city and the activities during it.', 'A plan to build a new railway station.', 'A family moving to another country.', 'A guide to choosing a restaurant job.'], correctIndex: 0 },
    { prompt: 'Detail · What did the travellers do after checking the map?', answers: ['They found a small café near the station.', 'They cancelled the trip.', 'They bought a train.', 'They returned home immediately.'], correctIndex: 0 },
    { prompt: 'Inference · Why is the visit to the museum notable?', answers: ['They continued with their plans despite the rain.', 'The museum was closed for the week.', 'They had planned to work there.', 'The weather improved before they left.'], correctIndex: 0 },
    { prompt: 'Purpose · Why does the writer mention buying a gift?', answers: ['To add a personal detail from the return journey.', 'To explain why the museum was closed.', 'To show that the travellers missed the train.', 'To introduce a discussion about prices.'], correctIndex: 0 },
  ],
  B1: [
    { prompt: 'Main idea · What is the community trying to do?', answers: ['Improve a public space by gathering opinions and testing a proposal.', 'Close the local market permanently.', 'Replace all public meetings with a survey.', 'Move residents to another neighbourhood.'], correctIndex: 0 },
    { prompt: 'Detail · What concern did some residents raise?', answers: ['Narrow sidewalks make it difficult to pass.', 'The square has too many libraries.', 'The market is open too early.', 'There are no homes near the square.'], correctIndex: 0 },
    { prompt: 'Inference · Why is the first phase temporary?', answers: ['The community wants to observe results and make adjustments if needed.', 'The design has already been rejected.', 'The shops will soon leave the area.', 'The city plans to stop collecting feedback.'], correctIndex: 0 },
    { prompt: 'Supporting evidence · Which action shows that the proposal can be revised?', answers: ['The city will compare actual use with initial expectations.', 'The city will avoid speaking with visitors.', 'The design will prevent access to shops.', 'The trial will end before it begins.'], correctIndex: 0 },
  ],
  B2: [
    { prompt: 'Main idea · What is the central issue in the transport proposal?', answers: ['Potential benefits must be weighed against funding, access, and disruption.', 'New vehicles will eliminate every transport expense.', 'The proposal concerns only train ticket prices.', 'Construction has already solved traffic congestion.'], correctIndex: 0 },
    { prompt: 'Detail · What is one possible benefit of more frequent service?', answers: ['Shorter waiting times.', 'Guaranteed lower fares.', 'No need for train connections.', 'An end to all road construction.'], correctIndex: 0 },
    { prompt: 'Inference · Why does the passage recommend a pilot?', answers: ['It can reveal unintended effects before wider implementation.', 'It removes the need for public funding.', 'It ensures all neighbourhoods have identical needs.', 'It replaces the need to publish evaluation criteria.'], correctIndex: 0 },
    { prompt: 'Author’s stance · How does the writer approach the proposal?', answers: ['Cautiously, noting benefits alongside conditions and risks.', 'Unreservedly, claiming success is certain.', 'Dismissively, rejecting public transport in general.', 'Indifferently, avoiding any evaluation.'], correctIndex: 0 },
  ],
  C1: [
    { prompt: 'Main conclusion · What does the report establish?', answers: ['Waiting times fell, but the evidence does not prove the schedule change was the sole cause.', 'The schedule change improved every route equally.', 'Interviews proved that the study covered all seasons.', 'The report established that no other factors matter.'], correctIndex: 0 },
    { prompt: 'Methodological limitation · What limits the study?', answers: ['It was brief, compared different neighbourhoods, and did not isolate every factor.', 'It relied exclusively on interviews over many years.', 'It measured no waiting times.', 'It excluded all bus routes from the city.'], correctIndex: 0 },
    { prompt: 'Inference · Why might the average be misleading?', answers: ['It can hide longer waits for particular routes or passengers.', 'It necessarily records every passenger’s experience.', 'It proves the service is equally reliable everywhere.', 'It removes the need to examine separate routes.'], correctIndex: 0 },
    { prompt: 'Recommended next step · What do the authors recommend?', answers: ['Extend observation and analyse results by route, time, and connection.', 'Stop collecting data and declare the plan successful.', 'Replace route data with a single citywide average.', 'Exclude interviews from any future assessment.'], correctIndex: 0 },
  ],
  C2: [
    { prompt: 'Main argument · What is the committee’s position?', answers: ['It accepts the reform’s aim but questions whether this design meets it without shifting costs.', 'It opposes every form of reform.', 'It considers average speed a complete measure of success.', 'It concludes that all routes benefited equally.'], correctIndex: 0 },
    { prompt: 'Qualification · Why is the speed increase insufficient evidence?', answers: ['It does not capture connection reliability, geographic differences, or other schedule changes.', 'It was measured on every route for several years.', 'It proves that costs were evenly distributed.', 'It shows that passengers no longer need transfers.'], correctIndex: 0 },
    { prompt: 'Inference · What does the committee imply about the early results?', answers: ['They may reflect both genuine benefits and measurement conditions favouring some routes.', 'They are necessarily false because they are preliminary.', 'They demonstrate that no further data are needed.', 'They show that all passengers have flexible schedules.'], correctIndex: 0 },
    { prompt: 'Best-supported conclusion · What can be concluded for now?', answers: ['Some journeys improved, but overall fairness and sustainability remain unproven.', 'The entire system has become fair and sustainable.', 'The reform produced no benefit on any journey.', 'The committee has already approved full implementation.'], correctIndex: 0 },
  ],
}
const profiles: Record<AddedLanguage, LanguageProfile> = {
  'Mandarin Chinese': {
    name: 'Mandarin Chinese', code: 'zh-CN', script: 'Hans',
    starter: ['你好 (nǐ hǎo)|hello', '谢谢 (xièxie)|thank you', '再见 (zàijiàn)|goodbye'],
    phrases: {
      A1: [
        { target: '你好 (nǐ hǎo)', english: 'hello', title: 'greeting someone' }, { target: '我叫安娜 (wǒ jiào Ānnà)', english: 'my name is Anna', title: 'introducing yourself' }, { target: '这是我的家人 (zhè shì wǒ de jiārén)', english: 'this is my family', title: 'talking about family' }, { target: '这是一本书 (zhè shì yì běn shū)', english: 'this is a book', title: 'naming everyday objects' }, { target: '我喜欢喝茶 (wǒ xǐhuan hē chá)', english: 'I like drinking tea', title: 'choosing food and drinks' }, { target: '这个多少钱 (zhège duōshao qián)', english: 'how much is this', title: 'asking a price' }, { target: '现在是三点 (xiànzài shì sān diǎn)', english: 'it is three o’clock now', title: 'saying the time' }, { target: '学校在前面 (xuéxiào zài qiánmiàn)', english: 'the school is ahead', title: 'finding places' }, { target: '请一直走 (qǐng yìzhí zǒu)', english: 'please go straight', title: 'following directions' }, { target: '我每天学习中文 (wǒ měitiān xuéxí Zhōngwén)', english: 'I study Chinese every day', title: 'describing a daily activity' },
      ],
      A2: [
        { target: '我早上七点起床 (wǒ zǎoshang qī diǎn qǐchuáng)', english: 'I get up at seven in the morning', title: 'describing a routine' }, { target: '我想买一件衬衫 (wǒ xiǎng mǎi yí jiàn chènshān)', english: 'I want to buy a shirt', title: 'shopping for essentials' }, { target: '请给我一碗面 (qǐng gěi wǒ yì wǎn miàn)', english: 'please give me a bowl of noodles', title: 'ordering a meal' }, { target: '我们周末见面吧 (wǒmen zhōumò jiànmiàn ba)', english: 'let’s meet this weekend', title: 'making plans' }, { target: '火车几点出发 (huǒchē jǐ diǎn chūfā)', english: 'what time does the train leave', title: 'travelling by train' }, { target: '我想预约医生 (wǒ xiǎng yùyuē yīshēng)', english: 'I would like to make a doctor’s appointment', title: 'making an appointment' }, { target: '我的房间有一扇大窗户 (wǒ de fángjiān yǒu yí shàn dà chuānghu)', english: 'my room has a large window', title: 'describing a home' }, { target: '今天比昨天冷 (jīntiān bǐ zuótiān lěng)', english: 'today is colder than yesterday', title: 'talking about the weather' }, { target: '上个周末我去了公园 (shàng ge zhōumò wǒ qù le gōngyuán)', english: 'I went to the park last weekend', title: 'sharing a past event' }, { target: '你可以帮我一下吗 (nǐ kěyǐ bāng wǒ yíxià ma)', english: 'could you help me for a moment', title: 'making a polite request' },
      ],
      B1: [
        { target: '那次旅行让我学会了临时调整计划 (nà cì lǚxíng ràng wǒ xuéhuì le línshí tiáozhěng jìhuà)', english: 'that trip taught me to adjust plans at short notice', title: 'telling a personal story' }, { target: '火车晚点以后，我们改乘了公共汽车 (huǒchē wǎndiǎn yǐhòu, wǒmen gǎi chéng le gōnggòng qìchē)', english: 'after the train was delayed, we took a bus instead', title: 'solving a travel problem' }, { target: '我希望明年能在这个领域继续学习 (wǒ xīwàng míngnián néng zài zhège lǐngyù jìxù xuéxí)', english: 'I hope to continue studying in this field next year', title: 'explaining a goal' }, { target: '社区正在讨论如何改善附近的公园 (shèqū zhèngzài tǎolùn rúhé gǎishàn fùjìn de gōngyuán)', english: 'the community is discussing how to improve the nearby park', title: 'following local news' }, { target: '首先收集资料，然后比较不同的结果 (shǒuxiān shōují zīliào, ránhòu bǐjiào bùtóng de jiéguǒ)', english: 'first collect information, then compare different results', title: 'explaining a process' }, { target: '虽然方案甲比较便宜，方案乙更方便 (suīrán fāngàn jiǎ bǐjiào piányi, fāngàn yǐ gèng fāngbiàn)', english: 'although option A is cheaper, option B is more convenient', title: 'comparing options' }, { target: '如果你提前准备，就会更有信心 (rúguǒ nǐ tíqián zhǔnbèi, jiù huì gèng yǒu xìnxīn)', english: 'if you prepare in advance, you will feel more confident', title: 'giving advice' }, { target: '我认为这个建议值得认真考虑 (wǒ rènwéi zhège jiànyì zhídé rènzhēn kǎolǜ)', english: 'I think this suggestion deserves careful consideration', title: 'sharing an opinion' }, { target: '这个节日保留了许多当地的传统 (zhège jiérì bǎoliú le xǔduō dāngdì de chuántǒng)', english: 'this festival preserves many local traditions', title: 'describing a tradition' }, { target: '天气好的话，我们可能会去郊外 (tiānqì hǎo de huà, wǒmen kěnéng huì qù jiāowài)', english: 'if the weather is good, we may go to the countryside', title: 'discussing possibilities' },
      ],
      B2: [
        { target: '这个方案有明显的优势，但也需要考虑长期成本 (zhège fāngàn yǒu míngxiǎn de yōushì, dàn yě xūyào kǎolǜ chángqī chéngběn)', english: 'this proposal has clear benefits, but long-term costs also need consideration', title: 'building a balanced argument' }, { target: '增加班次可以缩短等候时间，同时减少拥挤 (zēngjiā bāncì kěyǐ suōduǎn děnghòu shíjiān, tóngshí jiǎnshǎo yōngjǐ)', english: 'more frequent service can reduce waiting and crowding', title: 'discussing public transport' }, { target: '在批准之前，我们应该评估可能产生的影响 (zài pīzhǔn zhīqián, wǒmen yīnggāi pínggū kěnéng chǎnshēng de yǐngxiǎng)', english: 'before approval, we should assess the possible effects', title: 'evaluating a proposal' }, { target: '清楚的反馈有助于团队及时解决问题 (qīngchu de fǎnkuì yǒuzhùyú tuánduì jíshí jiějué wèntí)', english: 'clear feedback helps a team address problems promptly', title: 'communicating at work' }, { target: '便利的技术也可能收集超出必要范围的数据 (biànlì de jìshù yě kěnéng shōují chāochū bìyào fànwéi de shùjù)', english: 'convenient technology may also collect more data than necessary', title: 'discussing privacy' }, { target: '改变个人习惯很重要，完善公共服务同样重要 (gǎibiàn gèrén xíguàn hěn zhòngyào, wánshàn gōnggòng fúwù tóngyàng zhòngyào)', english: 'changing personal habits matters, as does improving public services', title: 'considering environmental choices' }, { target: '报告指出了趋势，但没有解释所有原因 (bàogào zhǐchū le qūshì, dàn méiyǒu jiěshì suǒyǒu yuányīn)', english: 'the report identifies a trend but does not explain every cause', title: 'interpreting a report' }, { target: '双方同意先试行三个月，再根据结果协商 (shuāngfāng tóngyì xiān shìxíng sān ge yuè, zài gēnjù jiéguǒ xiéshāng)', english: 'both sides agreed to a three-month trial before negotiating again', title: 'negotiating an agreement' }, { target: '有说服力的报道应当区分事实与评论 (yǒu shuōfúlì de bàodào yīngdāng qūfēn shìshí yǔ pínglùn)', english: 'persuasive reporting should distinguish facts from commentary', title: 'evaluating media' }, { target: '若不及时维护，短期节省可能导致更高的后续费用 (ruò bù jíshí wéihù, duǎnqī jiéshěng kěnéng dǎozhì gèng gāo de hòuxù fèiyòng)', english: 'without timely maintenance, short-term savings may cause higher later costs', title: 'explaining consequences' },
      ],
      C1: [
        { target: '这项发现与假设相符，但不足以单独证明因果关系 (zhè xiàng fāxiàn yǔ jiǎshè xiāngfú, dàn bùzúyǐ dāndú zhèngmíng yīnguǒ guānxì)', english: 'this finding is consistent with the hypothesis but cannot alone prove causation', title: 'qualifying a claim' }, { target: '两种解释都能说明部分证据，却各有局限 (liǎng zhǒng jiěshì dōu néng shuōmíng bùfen zhèngjù, què gè yǒu júxiàn)', english: 'both explanations account for some evidence, yet each has limits', title: 'weighing competing evidence' }, { target: '谨请贵方说明该决定所依据的评估标准 (jǐn qǐng guìfāng shuōmíng gāi juédìng suǒ yījù de pínggū biāozhǔn)', english: 'please clarify the evaluation criteria underlying this decision', title: 'writing formally' }, { target: '政策目标明确，并不意味着执行条件已经具备 (zhèngcè mùbiāo míngquè, bìng bù yìwèizhe zhíxíng tiáojiàn yǐjīng jùbèi)', english: 'a clear policy goal does not mean implementation conditions are in place', title: 'examining implementation' }, { target: '样本范围和观察时间限制了结论的适用性 (yàngběn fànwéi hé guānchá shíjiān xiànzhì le jiélùn de shìyòngxìng)', english: 'the sample and observation period limit how far the conclusion applies', title: 'discussing research limits' }, { target: '同一句话在不同场合可能产生截然不同的语气 (tóng yí jù huà zài bùtóng chǎnghé kěnéng chǎnshēng jiérán bùtóng de yǔqì)', english: 'the same sentence may convey a very different tone in another setting', title: 'noticing register' }, { target: '制度安排只有得到持续执行，才能产生预期效果 (zhìdù ānpái zhǐyǒu dédào chíxù zhíxíng, cái néng chǎnshēng yùqī xiàoguǒ)', english: 'institutional arrangements work as intended only when consistently implemented', title: 'analysing institutions' }, { target: '两项指标同时变化，并不能说明其中一项导致另一项 (liǎng xiàng zhǐbiāo tóngshí biànhuà, bìng bù néng shuōmíng qízhōng yí xiàng dǎozhì lìng yí xiàng)', english: 'two measures changing together does not show that one caused the other', title: 'separating cause and correlation' }, { target: '综合这些观点时，仍须保留它们之间的实质分歧 (zōnghé zhèxiē guāndiǎn shí, réng xū bǎoliú tāmen zhījiān de shízhì fēnqí)', english: 'a synthesis should preserve the substantive disagreement between these views', title: 'synthesizing viewpoints' }, { target: '换一种表述可以澄清争议，却不应掩盖核心问题 (huàn yì zhǒng biǎoshù kěyǐ chéngqīng zhēngyì, què bù yīng yǎngài héxīn wèntí)', english: 'reframing can clarify a dispute without obscuring its central issue', title: 'reframing disagreement' },
      ],
      C2: [
        { target: '他表面上表示赞同，措辞却为进一步质疑留下了余地 (tā biǎomiàn shàng biǎoshì zàntóng, cuòcí què wèi jìnyíbù zhìyí liúxià le yúdì)', english: 'while appearing to agree, his wording leaves room for further doubt', title: 'reading implicit meaning' }, { target: '在证据尚不完整时，精确表达不确定性尤为重要 (zài zhèngjù shàng bù wánzhěng shí, jīngquè biǎodá bù quèdìngxìng yóuwéi zhòngyào)', english: 'when evidence is incomplete, expressing uncertainty precisely is especially important', title: 'communicating uncertainty' }, { target: '结尾没有给出定论，而是重新解释了开篇的意象 (jiéwěi méiyǒu gěichū dìnglùn, ér shì chóngxīn jiěshì le kāipiān de yìxiàng)', english: 'the ending offers no firm resolution, instead recasting the opening image', title: 'interpreting literary ambiguity' }, { target: '承认这一点并不等于接受对方的全部结论 (chéngrèn zhè yìdiǎn bìng bù děngyú jiēshòu duìfāng de quánbù jiélùn)', english: 'conceding this point does not mean accepting the other side’s full conclusion', title: 'understanding a concession' }, { target: '若脱离具体语境，这种表达容易显得生硬甚至失礼 (ruò tuōlí jùtǐ yǔjìng, zhè zhǒng biǎodá róngyì xiǎnde shēngyìng shènzhì shīlǐ)', english: 'outside its context, this expression can sound stiff or even impolite', title: 'adapting register' }, { target: '她以委婉的措辞提出了实质上尖锐的反对意见 (tā yǐ wěiwǎn de cuòcí tíchū le shízhì shàng jiāruì de fǎnduì yìjiàn)', english: 'she voiced a substantive objection in tactful language', title: 'interpreting subtle disagreement' }, { target: '任何综合都必须说明证据之间无法消除的张力 (rènhé zōnghé dōu bìxū shuōmíng zhèngjù zhījiān wúfǎ xiāochú de zhānglì)', english: 'any synthesis must explain the irreducible tensions between the evidence', title: 'synthesizing complex evidence' }, { target: '这个说法言简意赅，却暗含了对前提的重新界定 (zhège shuōfǎ yánjiǎn yìgāi, què ànhán le duì qiántí de chóngxīn jièdìng)', english: 'the concise expression implicitly redefines the premise', title: 'recognizing idiomatic nuance' }, { target: '反例削弱了普遍性主张，却未必推翻其核心观察 (fǎnlì xuēruò le pǔbiànxìng zhǔzhāng, què wèibì tuīfān qí héxīn guānchá)', english: 'a counterexample weakens a universal claim without necessarily overturning its core observation', title: 'evaluating a counterargument' }, { target: '这种区分看似细微，却会改变责任归属的判断 (zhè zhǒng qūfēn kàn sì xìwēi, què huì gǎibiàn zérèn guīshǔ de pànduàn)', english: 'the distinction seems slight, yet changes how responsibility is assigned', title: 'expressing a fine distinction' },
      ],
    },
    reading: {
      A1: '我每天在家学习中文。我读书，也听简单的对话。朋友问我问题，我慢慢回答。今天我学了新词，明天我还会练习。',
      A2: '上个星期，我和朋友坐火车去了附近的城市。我们先看了地图，然后找到了车站旁边的小饭馆。虽然下雨了，我们还是参观了博物馆。回家的路上，我给家人买了礼物。',
      B1: '社区最近开始讨论如何让公共空间更方便。有人建议增加长椅和树木，也有人担心维护费用。我们收集了居民的意见，并比较了几个方案。经过讨论，大家决定先进行短期试行，再根据实际情况调整。',
      B2: '一项新的交通计划提出增加公交班次，并改善车站之间的连接。支持者认为，这会减少通勤时间，让更多居民不必开车。另一方面，实施计划需要稳定的资金，也可能暂时影响道路施工。评估方案时，既要观察平均数据，也要了解不同社区受到的影响。',
      C1: '报告显示，参与者使用该服务的次数有所增加，但这并不能直接证明服务改善了他们的生活。样本主要来自已经熟悉该项目的人，观察时间也较短。若要判断长期效果，还需要纳入不同地区的参与者，采用可比较的指标，并说明哪些变化可能由其他因素造成。',
      C2: '委员会并未否定改革的必要性，而是质疑当前方案能否实现其承诺。某些数据确实显示短期效率有所提高，但这种提升并未均匀分布，也可能以增加一线人员的负担为代价。因此，若把平均结果当作整体成效，便会掩盖重要差异。更审慎的结论应同时说明可观察到的收益、证据的边界，以及尚未解决的分配问题。',
    },
    grammar: {
      A1: [{ title: 'Basic Mandarin word order', summary: 'Build clear subject–verb–object sentences.', explanation: 'Mandarin commonly uses subject + verb + object. Adjectives can act as predicates with 很 (hěn), and Mandarin verbs do not conjugate for person.', examples: ['我喝茶。— I drink tea.', '她很忙。— She is busy.'] }, { title: 'Measure words and 的', summary: 'Use measure words with numbers and 的 to link descriptions.', explanation: 'A number before a noun usually needs a measure word. 的 (de) connects a modifier or possessor to a noun.', examples: ['一本书 — one book', '我的朋友 — my friend'] }],
      A2: [{ title: 'Questions and negation', summary: 'Ask yes/no and information questions and negate statements.', explanation: 'Add 吗 (ma) for many yes/no questions; question words stay where the answer would go. Use 不 (bù) for many present/future negatives and 没 (méi) for non-occurrence or lack.', examples: ['你喜欢茶吗？— Do you like tea?', '我没去。— I did not go.'] }, { title: 'Aspect with 了 and 过', summary: 'Describe completed events and experience.', explanation: '了 often marks a changed or completed situation; 过 marks experience. Neither is a direct equivalent of English past tense.', examples: ['我买了书。— I bought a book.', '我去过北京。— I have been to Beijing.'] }],
      B1: [{ title: 'Complements and result', summary: 'Show results and ability with verb complements.', explanation: 'A result complement follows a verb to show its outcome. 得 can introduce how well an action is performed.', examples: ['我听懂了。— I understood (by listening).', '她说得很清楚。— She speaks very clearly.'] }, { title: '把 and 被 constructions', summary: 'Emphasize an affected object or a recipient of an action.', explanation: '把 places a known object before the verb when the sentence describes what happens to it. 被 marks many passive constructions.', examples: ['请把门关上。— Please close the door.', '文件被寄出了。— The document was sent.'] }],
      B2: [{ title: '把 constructions in context', summary: 'Use 把 when an action affects a specific object.', explanation: 'A 把 sentence foregrounds how a specific object is handled; the verb phrase normally includes a result, direction, or other complement.', examples: ['她把问题解释清楚了。— She explained the issue clearly.', '我们把计划改好了。— We revised the plan.'] }, { title: 'Linked clauses and concessions', summary: 'Connect conditions, contrasts, and consequences.', explanation: 'Pairs such as 虽然…但是… and 即使…也… make relations between clauses explicit. Choose the pair that matches the intended logic.', examples: ['虽然很忙，但是他来了。— Although busy, he came.', '即使下雨，我们也出发。— Even if it rains, we will leave.'] }],
      C1: [{ title: 'Formal written connectors', summary: 'Use formal linking expressions to structure complex arguments.', explanation: 'Expressions such as 鉴于, 此外, and 因此 clarify the relation between evidence, qualifications, and conclusions in formal writing.', examples: ['鉴于现有证据，仍需进一步研究。— In view of the evidence, further research is still needed.', '此外，报告没有说明样本来源。— In addition, the report does not state the sample source.'] }, { title: 'Reported claims and stance', summary: 'Attribute claims and distinguish evidence from interpretation.', explanation: 'Use 据…所述 or 研究指出 to attribute information; qualify what the evidence supports rather than presenting an inference as established fact.', examples: ['研究指出两者有关联，但未证明因果。— The study notes an association but does not prove causation.', '据报告所述，变化并非均匀发生。— According to the report, the change was not uniform.'] }],
      C2: [{ title: 'Concession and implication', summary: 'Interpret what a speaker concedes without accepting the full claim.', explanation: 'Concessive framing can acknowledge a limited point while restricting its consequences. Attend to scope and what remains asserted.', examples: ['即便承认这一点，也不能由此得出相同结论。— Even granting this point does not lead to the same conclusion.', '话虽如此，关键问题仍未解决。— That said, the central issue remains unresolved.'] }, { title: 'Register and rhetorical precision', summary: 'Adjust wording to context and preserve subtle distinctions.', explanation: 'Formal Chinese often uses compact written constructions. Rephrase only when the new wording preserves scope, emphasis, and interpersonal tone.', examples: ['这一判断并非毫无根据，但适用范围有限。— The judgment is not groundless, but its scope is limited.', '与其说是拒绝，不如说是暂缓决定。— It is less a refusal than a postponement.'] }],
    },
  },
  'Modern Standard Arabic': {
    name: 'Modern Standard Arabic', code: 'ar', script: 'Arab',
    starter: ['مَرْحَبًا (marḥaban)|hello', 'شُكْرًا (shukran)|thank you', 'إِلَى اللِّقَاءِ (ilā al-liqāʾ)|goodbye'],
    phrases: {
      A1: [
        { target: 'مَرْحَبًا (marḥaban)', english: 'hello', title: 'greeting someone' }, { target: 'اِسْمِي أَنَا (ismī Anā)', english: 'my name is Anna', title: 'introducing yourself' }, { target: 'هَذِهِ أُسْرَتِي (hādhihi usratī)', english: 'this is my family', title: 'talking about family' }, { target: 'هَذَا كِتَابٌ (hādhā kitābun)', english: 'this is a book', title: 'naming everyday objects' }, { target: 'أُحِبُّ شُرْبَ الشَّايِ (uḥibbu shurba ash-shāy)', english: 'I like drinking tea', title: 'choosing food and drinks' }, { target: 'بِكَمْ هَذَا؟ (bikam hādhā)', english: 'how much is this?', title: 'asking a price' }, { target: 'السَّاعَةُ الثَّالِثَةُ الآنَ (as-sāʿatu ath-thālithatu al-āna)', english: 'it is three o’clock now', title: 'saying the time' }, { target: 'الْمَدْرَسَةُ أَمَامَنَا (al-madrasatu amāmanā)', english: 'the school is in front of us', title: 'finding places' }, { target: 'اِذْهَبْ مُبَاشَرَةً، مِنْ فَضْلِكَ (idhhab mubāsharatan, min faḍlik)', english: 'go straight, please', title: 'following directions' }, { target: 'أَدْرُسُ الْعَرَبِيَّةَ كُلَّ يَوْمٍ (adrusu al-ʿarabiyyata kulla yawmin)', english: 'I study Arabic every day', title: 'describing a daily activity' },
      ],
      A2: [
        { target: 'أَسْتَيْقِظُ فِي السَّاعَةِ السَّابِعَةِ (astayqiẓu fī as-sāʿati as-sābiʿa)', english: 'I wake up at seven', title: 'describing a routine' }, { target: 'أُرِيدُ شِرَاءَ قَمِيصٍ (urīdu shirāʾa qamīṣin)', english: 'I want to buy a shirt', title: 'shopping for essentials' }, { target: 'مِنْ فَضْلِكَ، أَعْطِنِي طَبَقًا مِنَ الْأَرُزِّ (min faḍlik, aʿṭinī ṭabaqan mina al-aruzz)', english: 'please give me a plate of rice', title: 'ordering a meal' }, { target: 'لِنَلْتَقِ فِي نِهَايَةِ الْأُسْبُوعِ (linaltaqi fī nihāyati al-usbūʿ)', english: 'let us meet at the weekend', title: 'making plans' }, { target: 'مَتَى يَغَادِرُ الْقِطَارُ؟ (matā yughādiru al-qiṭār)', english: 'when does the train leave?', title: 'travelling by train' }, { target: 'أُرِيدُ مَوْعِدًا مَعَ الطَّبِيبِ (urīdu mawʿidan maʿa aṭ-ṭabīb)', english: 'I would like an appointment with the doctor', title: 'making an appointment' }, { target: 'فِي غُرْفَتِي نَافِذَةٌ كَبِيرَةٌ (fī ghurfatī nāfidhatun kabīratun)', english: 'there is a large window in my room', title: 'describing a home' }, { target: 'الْيَوْمُ أَبْرَدُ مِنَ الْأَمْسِ (al-yawmu abradu mina al-ams)', english: 'today is colder than yesterday', title: 'talking about the weather' }, { target: 'ذَهَبْتُ إِلَى الْحَدِيقَةِ الأُسْبُوعَ الْمَاضِيَ (dhahabtu ilā al-ḥadīqati al-usbūʿa al-māḍiya)', english: 'I went to the park last week', title: 'sharing a past event' }, { target: 'هَلْ يُمْكِنُكَ مُسَاعَدَتِي؟ (hal yumkinuka musāʿadatī)', english: 'could you help me?', title: 'making a polite request' },
      ],
      B1: [
        { target: 'عَلَّمَتْنِي تِلْكَ الرِّحْلَةُ أَنْ أُعِيدَ تَرْتِيبَ خُطَطِي (ʿallamatnī tilka ar-riḥlatu an uʿīda tartība khuṭaṭī)', english: 'that trip taught me to adjust my plans', title: 'telling a personal story' }, { target: 'بَعْدَ تَأَخُّرِ الْقِطَارِ، سَافَرْنَا بِالْحَافِلَةِ (baʿda taʾakhkhuri al-qiṭār, sāfarnā bil-ḥāfila)', english: 'after the train was delayed, we travelled by bus', title: 'solving a travel problem' }, { target: 'أَتَمَنَّى أَنْ أُوَاصِلَ دِرَاسَتِي فِي هَذَا الْمَجَالِ (atamannā an uwāṣila dirāsatī fī hādhā al-majāl)', english: 'I hope to continue studying in this field', title: 'explaining a goal' }, { target: 'يَنَاقِشُ سُكَّانُ الْحَيِّ سُبُلَ تَحْسِينِ الْحَدِيقَةِ (yunāqishu sukkānu al-ḥayyi subula taḥsīni al-ḥadīqa)', english: 'neighborhood residents discuss ways to improve the park', title: 'following local news' }, { target: 'أَوَّلًا نَجْمَعُ الْمَعْلُومَاتِ، ثُمَّ نُقَارِنُ النَّتَائِجَ (awwalan najmaʿu al-maʿlūmāt, thumma nuqārinu an-natāʾij)', english: 'first we gather information, then compare results', title: 'explaining a process' }, { target: 'عَلَى الرَّغْمِ مِنْ أَنَّ الْخِيَارَ الأَوَّلَ أَرْخَصُ، فَالثَّانِي أَسْهَلُ (ʿalā ar-raghmi min anna al-khiyāra al-awwali arkhaṣ, fath-thānī ashal)', english: 'although the first option is cheaper, the second is easier', title: 'comparing options' }, { target: 'إِذَا اسْتَعْدَدْتَ مُبَكِّرًا، سَتَشْعُرُ بِثِقَةٍ أَكْبَرَ (idhā istaʿdadta mubakkiran, satashʿuru bithiqatin akbar)', english: 'if you prepare early, you will feel more confident', title: 'giving advice' }, { target: 'أَرَى أَنَّ هَذَا الِاقْتِرَاحَ يَسْتَحِقُّ الدِّرَاسَةَ (arā anna hādhā al-iqtirāḥa yastaḥiqqu ad-dirāsa)', english: 'I think this proposal deserves consideration', title: 'sharing an opinion' }, { target: 'يَحْفَظُ هَذَا الِاحْتِفَالُ تَقَالِيدَ مَحَلِّيَّةً كَثِيرَةً (yaḥfaẓu hādhā al-iḥtifālu taqālīda maḥalliyyatan kathīra)', english: 'this festival preserves many local traditions', title: 'describing a tradition' }, { target: 'إِذَا كَانَ الطَّقْسُ جَيِّدًا، فَرُبَّمَا نَذْهَبُ إِلَى الرِّيفِ (idhā kāna aṭ-ṭaqsu jayyidan, farubbamā nadhhabu ilā ar-rīf)', english: 'if the weather is good, perhaps we will go to the countryside', title: 'discussing possibilities' },
      ],
      B2: [
        { target: 'يُقَدِّمُ هَذَا الْمَقْتَرَحُ مَزَايَا وَاضِحَةً، لَكِنَّهُ يَتَطَلَّبُ دِرَاسَةَ التَّكَالِيفِ بَعِيدَةِ الْمَدَى (yuqaddimu hādhā al-muqta raḥu mazāyā wāḍiḥatan, lākinna-hu yataṭallabu dirāsata at-takālīfi baʿīdati al-madā)', english: 'the proposal offers clear benefits but requires study of long-term costs', title: 'building a balanced argument' }, { target: 'قَدْ يُقَلِّلُ تَكْثِيفُ الرَّحَلَاتِ وَقْتَ الِانْتِظَارِ وَالِاكْتِظَاظَ (qad yuqallilu takthīfu ar-raḥalāti waqta al-intiẓāri wal-iktiẓāẓ)', english: 'more frequent services may reduce waiting and crowding', title: 'discussing public transport' }, { target: 'يَنْبَغِي تَقْيِيمُ الآثَارِ الْمُحْتَمَلَةِ قَبْلَ الْمُوَافَقَةِ (yanbaghī taqyīmu al-āthāri al-muḥtamalati qabla al-muwāfaqa)', english: 'possible effects should be assessed before approval', title: 'evaluating a proposal' }, { target: 'تُسَاعِدُ الْمُلَاحَظَاتُ الْوَاضِحَةُ الْفَرِيقَ عَلَى مُعَالَجَةِ الْمُشْكِلَاتِ (tusāʿidu al-mulāḥaẓātu al-wāḍiḥatu al-farīqa ʿalā muʿālijati al-mushkilāt)', english: 'clear feedback helps a team address problems', title: 'communicating at work' }, { target: 'قَدْ تَجْمَعُ التِّقْنِيَةُ الْمُفِيدَةُ بَيَانَاتٍ تَتَجَاوَزُ الْحَاجَةَ (qad tajmaʿu at-tiqniyyatu al-mufīdatu bayānātin tatajāwazu al-ḥāja)', english: 'useful technology may collect data beyond what is needed', title: 'discussing privacy' }, { target: 'تَهُمُّ الْخِيَارَاتُ الْفَرْدِيَّةُ، كَمَا تَهُمُّ الْخَدَمَاتُ الْعَامَّةُ (tahummu al-khiyārātu al-fardiyyatu, kamā tahummu al-khadamātu al-ʿāmma)', english: 'individual choices matter, as do public services', title: 'considering environmental choices' }, { target: 'يُبَيِّنُ التَّقْرِيرُ اتِّجَاهًا، لَكِنَّهُ لَا يُفَسِّرُ جَمِيعَ الأَسْبَابِ (yubayyinu at-taqrīru ittijāhan, lākinna-hu lā yufassiru jamīʿa al-asbāb)', english: 'the report shows a trend but does not explain every cause', title: 'interpreting a report' }, { target: 'اتَّفَقَ الطَّرَفَانِ عَلَى تَجْرِبَةِ الْخُطَّةِ ثَلَاثَةَ أَشْهُرٍ (ittafaqa aṭ-ṭarafāni ʿalā tajribati al-khuṭṭati thalāthata ashhur)', english: 'both parties agreed to trial the plan for three months', title: 'negotiating an agreement' }, { target: 'يَنْبَغِي لِلتَّقْرِيرِ الْمُقْنِعِ أَنْ يُمَيِّزَ بَيْنَ الْحَقَائِقِ وَالتَّعْلِيقَاتِ (yanbaghī lit-taqrīri al-muqniʿi an yumayyiza bayna al-ḥaqāʾiqi wat-taʿlīqāt)', english: 'persuasive reporting should distinguish facts and commentary', title: 'evaluating media' }, { target: 'قَدْ يُؤَدِّي إِهْمَالُ الصِّيَانَةِ إِلَى تَكَالِيفَ لَاحِقَةٍ أَعْلَى (qad yuʾaddī ihmālu aṣ-ṣiyānati ilā takālīfa lāḥiqatin aʿlā)', english: 'neglecting maintenance may lead to higher later costs', title: 'explaining consequences' },
      ],
      C1: [
        { target: 'تَتَّفِقُ هَذِهِ النَّتِيجَةُ مَعَ الْفَرَضِيَّةِ، لَكِنَّهَا لَا تُثْبِتُ السَّبَبِيَّةَ وَحْدَهَا (tattafiqu hādhihi an-natījatu maʿa al-farḍiyya, lākinna-hā lā tuthbitu as-sababiyyata waḥdahā)', english: 'this finding fits the hypothesis but does not by itself establish causation', title: 'qualifying a claim' }, { target: 'يُفَسِّرُ كُلُّ تَأْوِيلٍ جُزْءًا مِنَ الأَدِلَّةِ، وَلَكِنَّ لَهُ حُدُودًا (yufassiru kullu taʾwīlin juzʾan mina al-adilla, walākinna lahu ḥudūdan)', english: 'each interpretation accounts for some evidence, but has limits', title: 'weighing competing evidence' }, { target: 'نَرْجُو تَوْضِيحَ مَعَايِيرِ التَّقْيِيمِ الَّتِي اسْتَنَدَ إِلَيْهَا الْقَرَارُ (narjū tawḍīḥa maʿāyīri at-taqyīmi allatī istanada ilayhā al-qarār)', english: 'please clarify the evaluation criteria on which the decision was based', title: 'writing formally' }, { target: 'وُضُوحُ هَدَفِ السِّيَاسَةِ لَا يَعْنِي تَوَافُرَ شُرُوطِ تَنْفِيذِهَا (wuḍūḥu hadafi as-siyāsati lā yaʿnī tawāfura shurūṭi tanfīdhihā)', english: 'a clear policy goal does not mean its implementation conditions are available', title: 'examining implementation' }, { target: 'يُقَيِّدُ حَجْمُ العَيِّنَةِ وَمُدَّةُ الْمُرَاقَبَةِ نِطَاقَ النَّتِيجَةِ (yuqayyidu ḥajmu al-ʿayyinati wa-mud’datu al-murāqabati niṭāqa an-natīja)', english: 'sample size and observation period limit the scope of the finding', title: 'discussing research limits' }, { target: 'قَدْ تَحْمِلُ الْعِبَارَةُ نَفْسُهَا نَبْرَةً مُخْتَلِفَةً بِاخْتِلَافِ السِّيَاقِ (qad taḥmilu al-ʿibāratu nafsuhā nabratan mukhtalifatan bikhtilāfi as-siyāq)', english: 'the same expression can carry a different tone depending on context', title: 'noticing register' }, { target: 'لَا تُحَقِّقُ التَّرْتِيبَاتُ الْمُؤَسَّسِيَّةُ أَثَرَهَا إِلَّا بِالتَّنْفِيذِ الْمُتَّسِقِ (lā tuḥaqiqu at-tartībātu al-muʾassasiyyatu atharahā illā bit-tanfīdhi al-muttasiq)', english: 'institutional arrangements achieve their effect only through consistent implementation', title: 'analysing institutions' }, { target: 'لَا يُثْبِتُ تَغَيُّرُ مُؤَشِّرَيْنِ مَعًا أَنَّ أَحَدَهُمَا سَبَّبَ الآخَرَ (lā yuthbitu taghayyuru muʾashshirayn maʿan anna aḥadahumā sababa al-ākhar)', english: 'two measures changing together does not prove one caused the other', title: 'separating cause and correlation' }, { target: 'يَجِبُ أَلَّا يُخْفِيَ التَّلْخِيصُ الْخِلَافَ الْجَوْهَرِيَّ بَيْنَ الآرَاءِ (yajibu allā yukhfiya at-talkhīṣu al-khilāfa al-jawhariyya bayna al-ārāʾ)', english: 'a synthesis should not hide substantive disagreements between views', title: 'synthesizing viewpoints' }, { target: 'قَدْ يُوَضِّحُ تَغْيِيرُ الصِّيَاغَةِ النِّزَاعَ مِنْ دُونِ إِغْفَالِ جَوْهَرِهِ (qad yūḍiḥu taghyīru aṣ-ṣiyāghati an-nizāʿa min dūni ighfāli jawharih)', english: 'rephrasing can clarify a dispute without overlooking its substance', title: 'reframing disagreement' },
      ],
      C2: [
        { target: 'يُبْدِي مُوَافَقَةً ظَاهِرِيَّةً، غَيْرَ أَنَّ صِيَاغَتَهُ تُبْقِي بَابَ التَّشْكِيكِ مَفْتُوحًا (yubdī muwāfaqatan ẓāhiriyyatan, ghayra anna ṣiyāghatahu tubqī bāba at-tashkīki maftūḥan)', english: 'he appears to agree, yet his wording leaves room for doubt', title: 'reading implicit meaning' }, { target: 'تَتَطَلَّبُ دِقَّةُ التَّعْبِيرِ عَنِ اللَّايَقِينِ أَدِلَّةً غَيْرَ مُكْتَمِلَةٍ (tataṭallabu diqqatu at-taʿbīri ʿani al-lāyaqīni adillatan ghayra muktamila)', english: 'precise expression of uncertainty matters when evidence is incomplete', title: 'communicating uncertainty' }, { target: 'لَا تَحْسِمُ النِّهَايَةُ المَعْنَى، بَلْ تُعِيدُ تَأْوِيلَ الصُّورَةِ الأُولَى (lā taḥsimu an-nihāyatu al-maʿnā, bal tuʿīdu taʾwīla aṣ-ṣūrati al-ūlā)', english: 'the ending does not settle the meaning but recasts the opening image', title: 'interpreting literary ambiguity' }, { target: 'لَا يَعْنِي الإِقْرَارُ بِهَذِهِ النُّقْطَةِ قَبُولَ النَّتِيجَةِ كُلِّهَا (lā yaʿnī al-iqrāru bihādhihi an-nuqṭati qabūla an-natījati kullihā)', english: 'conceding this point does not mean accepting the whole conclusion', title: 'understanding a concession' }, { target: 'قَدْ يَبْدُو التَّعْبِيرُ مُتَكَلَّفًا أَوْ فَظًّا خَارِجَ سِيَاقِهِ (qad yabdū at-taʿbīru mutakallifan aw faẓẓan khārija siyāqih)', english: 'an expression may sound forced or impolite outside its context', title: 'adapting register' }, { target: 'صَاغَتِ الِاعْتِرَاضَ الْجَوْهَرِيَّ بِلُغَةٍ لَبِقَةٍ (ṣāghati al-iʿtirāḍa al-jawhariyya bilughatin labiqatin)', english: 'she framed a substantive objection in tactful language', title: 'interpreting subtle disagreement' }, { target: 'يَكْشِفُ التَّلْخِيصُ الدَّقِيقُ مَوَاضِعَ التَّوَتُّرِ بَيْنَ الأَدِلَّةِ (yakshifu at-talkhīṣu ad-daqīqu mawāḍiʿa at-tawatturi bayna al-adilla)', english: 'a precise synthesis reveals tensions between pieces of evidence', title: 'synthesizing complex evidence' }, { target: 'يُعِيدُ هَذَا التَّعْبِيرُ تَعْرِيفَ المُسَلَّمَةِ ضِمْنًا بِإِيجَازٍ (yuʿīdu hādhā at-taʿbīru taʿrīfa al-musallamati ḍimnan bi-ījāz)', english: 'this concise expression implicitly redefines the premise', title: 'recognizing idiomatic nuance' }, { target: 'يُضْعِفُ المِثَالُ المُضَادُّ الادِّعَاءَ العَامَّ، وَلَا يَنْقُضُ المُشَاهَدَةَ الأَسَاسِيَّةَ بِالضَّرُورَةِ (yuḍʿifu al-mithālu al-muḍāddu al-iddaʿāʾa al-ʿāmma, wa-lā yanquḍu al-mushāhadata al-asāsiyyata biḍ-ḍarūra)', english: 'a counterexample weakens a general claim without necessarily refuting the core observation', title: 'evaluating a counterargument' }, { target: 'يُغَيِّرُ هَذَا التَّمْيِيزُ الدَّقِيقُ كَيْفِيَّةَ تَحْدِيدِ الْمَسْؤُولِيَّةِ (yughayyiru hādhā at-tamyīzu ad-daqīqu kayfiyyata taḥdīdi al-masʾūliyya)', english: 'this fine distinction changes how responsibility is assigned', title: 'expressing a fine distinction' },
      ],
    },
    reading: {
      A1: 'أَدْرُسُ اللُّغَةَ الْعَرَبِيَّةَ فِي الْبَيْتِ كُلَّ يَوْمٍ. أَقْرَأُ كَلِمَاتٍ جَدِيدَةً وَأَسْمَعُ حِوَارًا قَصِيرًا. يَسْأَلُنِي صَدِيقِي سُؤَالًا، فَأُجِيبُ بِبُطْءٍ. أَتَعَلَّمُ الْيَوْمَ وَأُرَاجِعُ غَدًا.',
      A2: 'فِي الأُسْبُوعِ الْمَاضِي سَافَرْتُ مَعَ صَدِيقٍ إِلَى مَدِينَةٍ قَرِيبَةٍ. قَرَأْنَا الْخَرِيطَةَ، ثُمَّ وَجَدْنَا مَطْعَمًا صَغِيرًا بِجَانِبِ الْمَحَطَّةِ. عَلَى الرَّغْمِ مِنَ الْمَطَرِ، زُرْنَا الْمَتْحَفَ وَاشْتَرَيْنَا هَدِيَّةً لِلْأُسْرَةِ.',
      B1: 'بَدَأَ سُكَّانُ الْحَيِّ مُؤَخَّرًا مُنَاقَشَةَ طُرُقِ تَحْسِينِ الْمَسَاحَاتِ الْعَامَّةِ. اقْتَرَحَ بَعْضُهُمْ زِيَادَةَ الْمَقَاعِدِ وَزِرَاعَةَ الأَشْجَارِ، بَيْنَمَا أَبْدَى آخَرُونَ قَلَقًا بِشَأْنِ تَكَالِيفِ الصِّيَانَةِ. جَمَعْنَا آراءَ السُّكَّانِ وَقَارَنَّا بَيْنَ خِيَارَاتٍ مُخْتَلِفَةٍ. وَفِي النِّهَايَةِ، قَرَّرَ الْمُشَارِكُونَ تَجْرِبَةَ أَحَدِ الْحُلُولِ مُؤَقَّتًا وَتَعْدِيلَهُ وَفْقَ النَّتَائِجِ.',
      B2: 'تَقْتَرِحُ خُطَّةُ النَّقْلِ الْجَدِيدَةُ زِيَادَةَ عَدَدِ الرَّحَلَاتِ وَتَحْسِينَ الرَّبْطِ بَيْنَ الْمَحَطَّاتِ. يَرَى مُؤَيِّدُوهَا أَنَّ ذَلِكَ سَيُقَلِّلُ وَقْتَ التَّنَقُّلِ وَيُخَفِّفُ الِاعْتِمَادَ عَلَى السَّيَّارَاتِ. فِي الْمُقَابِلِ، تَتَطَلَّبُ الْخُطَّةُ تَمْوِيلًا مُسْتَقِرًّا، وَقَدْ تُؤَثِّرُ أَعْمَالُ الْبِنَاءِ فِي حَرَكَةِ السَّيْرِ مُؤَقَّتًا. لِذَلِكَ يَنْبَغِي أَنْ يَشْمَلَ التَّقْيِيمُ مُتَوَسِّطَاتِ الْأَدَاءِ وَتَجَارِبَ الْمُجْتَمَعَاتِ الْمُخْتَلِفَةِ.',
      C1: 'يُشِيرُ التَّقْرِيرُ إِلَى زِيَادَةِ اسْتِخْدَامِ الْخِدْمَةِ بَيْنَ الْمُشَارِكِينَ، غَيْرَ أَنَّ ذَلِكَ لَا يُثْبِتُ مُبَاشَرَةً أَنَّهَا حَسَّنَتْ حَيَاتَهُمْ. فَقَدِ اقْتَصَرَتِ الْعَيِّنَةُ إِلَى حَدٍّ كَبِيرٍ عَلَى أَشْخَاصٍ يَعْرِفُونَ الْمَشْرُوعَ مُسْبَقًا، وَكَانَتْ فَتْرَةُ الْمُرَاقَبَةِ قَصِيرَةً. وَلِتَقْيِيمِ الأَثَرِ طَوِيلَ الْمَدَى، نَحْتَاجُ إِلَى مُشَارِكِينَ مِنْ مَنَاطِقَ مُتَعَدِّدَةٍ وَمُؤَشِّرَاتٍ قَابِلَةٍ لِلْمُقَارَنَةِ، مَعَ بَيَانِ الْعَوَامِلِ الأُخْرَى الَّتِي قَدْ تُفَسِّرُ التَّغَيُّرَ.',
      C2: 'لَمْ تَرْفُضِ اللَّجْنَةُ ضَرُورَةَ الإِصْلَاحِ، بَلْ تَسَاءَلَتْ عَمَّا إِذَا كَانَتِ الْخُطَّةُ الْحَالِيَّةُ قَادِرَةً عَلَى تَحْقِيقِ وُعُودِهَا. تُظْهِرُ بَعْضُ الْبَيَانَاتِ تَحَسُّنًا قَصِيرَ الأَمَدِ فِي الْكَفَاءَةِ، إِلَّا أَنَّ هَذَا التَّحَسُّنَ لَمْ يَتَوَزَّعْ بِالتَّسَاوِي، وَرُبَّمَا تَحَقَّقَ عَلَى حِسَابِ زِيَادَةِ الأَعْبَاءِ عَلَى الْعَامِلِينَ فِي الْمَيْدَانِ. وَعَلَيْهِ، فَإِنَّ اعْتِبَارَ الْمُتَوَسِّطَاتِ دَلِيلًا كَافِيًا عَلَى النَّجَاحِ يُخْفِي تَفَاوُتَ التَّجَارِبِ. وَيَنْبَغِي لِلْخُلَاصَةِ الأَكْثَرِ تَحَفُّظًا أَنْ تَذْكُرَ الْمَكَاسِبَ الْمُلَاحَظَةَ، وَحُدُودَ الأَدِلَّةِ، وَمَسْأَلَةَ التَّوْزِيعِ الَّتِي لَمْ تُحَلَّ بَعْدُ.',
    },
    grammar: {
      A1: [{ title: 'Arabic nominal and verbal sentences', summary: 'Recognize common sentence patterns and agreement.', explanation: 'Arabic can form a nominal sentence without a present-tense equivalent of “to be.” Verbal sentences commonly begin with a verb. Modern Standard Arabic has grammatical gender and number.', examples: ['الْبَيْتُ كَبِيرٌ — The house is large.', 'يَقْرَأُ الطَّالِبُ كِتَابًا — The student reads a book.'] }, { title: 'The definite article and adjective agreement', summary: 'Use ال and match adjectives to nouns.', explanation: 'الـ marks many definite nouns. Adjectives usually follow the noun and agree in definiteness, gender, and number.', examples: ['كِتَابٌ جَدِيدٌ — a new book', 'الْكُتُبُ الْجَدِيدَةُ — the new books'] }],
      A2: [{ title: 'Present tense and negation', summary: 'Use common imperfect forms and negate statements.', explanation: 'The imperfect verb changes with person and gender. لا commonly negates present statements; لَمْ with a jussive verb commonly negates a past event.', examples: ['أَكْتُبُ رِسَالَةً — I write a letter.', 'لَا أَعْرِفُ — I do not know.'] }, { title: 'Idāfa and possession', summary: 'Link nouns to express relationships and possession.', explanation: 'In an إضافة (iḍāfa) construction, two nouns form a close relationship. The first noun is usually indefinite without ال; the second is genitive.', examples: ['كِتَابُ الطَّالِبِ — the student’s book', 'مَحَطَّةُ الْقِطَارِ — the train station'] }],
      B1: [{ title: 'Past tense and time sequence', summary: 'Narrate completed actions and connect events.', explanation: 'The perfect verb commonly describes a completed event. Connectors such as بَعْدَ ذَلِكَ and بَيْنَمَا help show sequence and contrast.', examples: ['زُرْتُ الْمَدِينَةَ — I visited the city.', 'بَعْدَ ذَلِكَ عُدْنَا — After that, we returned.'] }, { title: 'Relative clauses', summary: 'Add information about a person or thing.', explanation: 'Relative pronouns such as الَّذِي and الَّتِي agree with the antecedent in gender and number. The relative clause provides identifying or descriptive information.', examples: ['الطَّالِبُ الَّذِي يَدْرُسُ — the student who studies', 'الْمَدِينَةُ الَّتِي زُرْتُهَا — the city that I visited'] }],
      B2: [{ title: 'Subordination and conditionals', summary: 'Express conditions, purposes, and concessions.', explanation: 'Formal Arabic uses patterns such as إِذَا…فَـ for likely conditions and عَلَى الرَّغْمِ مِنْ أَنَّ for concession. Verb mood depends on the construction.', examples: ['إِذَا وَصَلَ مُبَكِّرًا، سَنَبْدَأُ — If he arrives early, we will begin.', 'عَلَى الرَّغْمِ مِنَ الصُّعُوبَةِ، نَجَحَ — Despite the difficulty, he succeeded.'] }, { title: 'Passive voice and formal style', summary: 'Recognize passive constructions and formal phrasing.', explanation: 'Arabic passive verb patterns foreground an action when the agent is unknown or less relevant. Formal writing often uses precise nominal and verbal choices.', examples: ['أُعْلِنَتِ النَّتَائِجُ — The results were announced.', 'نُوقِشَ الْمَقْتَرَحُ — The proposal was discussed.'] }],
      C1: [{ title: 'Formal connectors and argument', summary: 'Structure a formal argument with explicit logical relations.', explanation: 'Connectors such as بِالإِضَافَةِ إِلَى ذَلِكَ, غَيْرَ أَنَّ, and بِنَاءً عَلَى ذَلِكَ distinguish addition, contrast, and inference.', examples: ['غَيْرَ أَنَّ النَّتَائِجَ تَحْتَاجُ إِلَى تَحَقُّقٍ — However, the results need verification.', 'بِنَاءً عَلَى ذَلِكَ، نَقْتَرِحُ تَعْدِيلَ الْخُطَّةِ — Accordingly, we propose revising the plan.'] }, { title: 'Attribution and evidential caution', summary: 'Attribute claims and qualify conclusions.', explanation: 'Use reporting verbs and sources to distinguish a finding from the writer’s inference. State the limits of a study before extending its conclusion.', examples: ['يُشِيرُ التَّقْرِيرُ إِلَى… — The report indicates…', 'لَا تَكْفِي هَذِهِ الْبَيَانَاتُ لِإِثْبَاتِ… — These data are insufficient to prove…'] }],
      C2: [{ title: 'Concession and scope', summary: 'Concede a limited point without surrendering the broader argument.', explanation: 'Concessive expressions can acknowledge one premise while limiting its scope. Track which claim is accepted and which remains contested.', examples: ['وَإِنْ سُلِّمَ بِذَلِكَ، فَلَا يَلْزَمُ عَنْهُ… — Even if that is granted, it does not follow that…', 'لَا يَعْنِي الإِقْرَارُ بِذَلِكَ قَبُولَ النَّتِيجَةِ — Acknowledging that does not mean accepting the conclusion.'] }, { title: 'Rhetorical register and nuance', summary: 'Interpret implication and choose a precise formal register.', explanation: 'In formal MSA, word choice and clause order can signal reservation, emphasis, or tact. Preserve those pragmatic effects when paraphrasing.', examples: ['يَبْدُو ذَلِكَ صَحِيحًا فِي الظَّاهِرِ — That appears correct on the surface.', 'وَلَعَلَّ الأَدَقَّ أَنْ نَقُولَ… — Perhaps it is more accurate to say…'] }],
    },
  },
  Russian: {
    name: 'Russian', code: 'ru-RU', script: 'Cyrl',
    starter: ['Здравствуйте (zdravstvuyte)|hello', 'Спасибо (spasibo)|thank you', 'До свидания (do svidaniya)|goodbye'],
    phrases: {
      A1: [
        { target: 'Здравствуйте (zdravstvuyte)', english: 'hello (polite)', title: 'greeting someone' }, { target: 'Меня зовут Анна (menya zovut Anna)', english: 'my name is Anna', title: 'introducing yourself' }, { target: 'Это моя семья (eto moya semya)', english: 'this is my family', title: 'talking about family' }, { target: 'Это книга (eto kniga)', english: 'this is a book', title: 'naming everyday objects' }, { target: 'Я люблю чай (ya lyublyu chay)', english: 'I like tea', title: 'choosing food and drinks' }, { target: 'Сколько это стоит? (skolko eto stoit)', english: 'how much does this cost?', title: 'asking a price' }, { target: 'Сейчас три часа (seychas tri chasa)', english: 'it is three o’clock now', title: 'saying the time' }, { target: 'Школа находится впереди (shkola nakhoditsya vperedi)', english: 'the school is ahead', title: 'finding places' }, { target: 'Идите прямо, пожалуйста (idite pryamo, pozhaluysta)', english: 'go straight, please', title: 'following directions' }, { target: 'Я каждый день изучаю русский язык (ya kazhdyy den izuchayu russkiy yazyk)', english: 'I study Russian every day', title: 'describing a daily activity' },
      ],
      A2: [
        { target: 'Я встаю в семь утра (ya vstayu v sem utra)', english: 'I get up at seven in the morning', title: 'describing a routine' }, { target: 'Я хочу купить рубашку (ya khochu kupit rubashku)', english: 'I want to buy a shirt', title: 'shopping for essentials' }, { target: 'Принесите, пожалуйста, суп (prinesite pozhaluysta sup)', english: 'please bring the soup', title: 'ordering a meal' }, { target: 'Давай встретимся в выходные (davay vstretimsya v vykhodnye)', english: 'let’s meet at the weekend', title: 'making plans' }, { target: 'Во сколько отправляется поезд? (vo skolko otpravlyaetsya poyezd)', english: 'what time does the train leave?', title: 'travelling by train' }, { target: 'Мне нужно записаться к врачу (mne nuzhno zapisatsya k vrachu)', english: 'I need to make a doctor’s appointment', title: 'making an appointment' }, { target: 'В моей комнате большое окно (v moyey komnate bolshoye okno)', english: 'there is a large window in my room', title: 'describing a home' }, { target: 'Сегодня холоднее, чем вчера (segodnya kholodnee chem vchera)', english: 'today is colder than yesterday', title: 'talking about the weather' }, { target: 'В прошлые выходные я ходил в парк (v proshlye vykhodnye ya khodil v park)', english: 'I went to the park last weekend (masculine speaker)', title: 'sharing a past event' }, { target: 'Не могли бы вы мне помочь? (ne mogli by vy mne pomoch)', english: 'could you help me?', title: 'making a polite request' },
      ],
      B1: [
        { target: 'Та поездка научила меня менять планы в последний момент (ta poyezdka nauchila menya menyat plany v posledniy moment)', english: 'that trip taught me to change plans at the last moment', title: 'telling a personal story' }, { target: 'После задержки поезда мы поехали на автобусе (posle zaderzhki poyezda my poyekhali na avtobuse)', english: 'after the train delay, we travelled by bus', title: 'solving a travel problem' }, { target: 'Я надеюсь продолжить обучение в этой области (ya nadeyus prodolzhit obucheniye v etoy oblasti)', english: 'I hope to continue studying in this field', title: 'explaining a goal' }, { target: 'Жители района обсуждают, как улучшить парк (zhiteli rayona obsuzhdayut kak uluchshit park)', english: 'residents discuss how to improve the park', title: 'following local news' }, { target: 'Сначала соберите данные, затем сравните результаты (snachala soberite dannyye zatem sravnite rezultaty)', english: 'first collect the data, then compare the results', title: 'explaining a process' }, { target: 'Хотя первый вариант дешевле, второй удобнее (khotya pervyy variant deshevle vtoroy udobneye)', english: 'although the first option is cheaper, the second is more convenient', title: 'comparing options' }, { target: 'Если подготовиться заранее, будет легче (yesli podgotovitsya zaranee budet legche)', english: 'if you prepare in advance, it will be easier', title: 'giving advice' }, { target: 'Я считаю, что это предложение заслуживает внимания (ya schitayu chto eto predlozheniye zasluzhivayet vnimaniya)', english: 'I think this proposal deserves attention', title: 'sharing an opinion' }, { target: 'Этот праздник сохраняет многие местные традиции (etot prazdnik sokhranyayet mnogiye mestnyye traditsii)', english: 'this festival preserves many local traditions', title: 'describing a tradition' }, { target: 'Если будет хорошая погода, возможно, мы поедем за город (yesli budet khoroshaya pogoda vozmozhno my poyedem za gorod)', english: 'if the weather is good, perhaps we will go outside the city', title: 'discussing possibilities' },
      ],
      B2: [
        { target: 'У этого предложения есть очевидные преимущества, но важно учитывать долгосрочные расходы (u etogo predlozheniya yest ochevidnyye preimushchestva no vazhno uchityvat dolgosrochnyye raskhody)', english: 'this proposal has clear advantages, but long-term costs matter too', title: 'building a balanced argument' }, { target: 'Более частые рейсы сократят ожидание и уменьшат скопление людей (boleye chastye reysy sokratyat ozhidaniye i umenshat skopleniye lyudey)', english: 'more frequent services will reduce waiting and crowding', title: 'discussing public transport' }, { target: 'До утверждения необходимо оценить возможные последствия (do utverzhdeniya neobkhodimo otsenit vozmozhnyye posledstviya)', english: 'possible consequences must be assessed before approval', title: 'evaluating a proposal' }, { target: 'Открытая обратная связь помогает команде быстрее решать проблемы (otkrytaya obratnaya svyaz pomogayet komande bystreye reshat problemy)', english: 'open feedback helps a team solve problems faster', title: 'communicating at work' }, { target: 'Удобные технологии могут собирать больше данных, чем необходимо (udobnyye tekhnologii mogut sobirat bolshe dannykh chem neobkhodimo)', english: 'convenient technologies may collect more data than necessary', title: 'discussing privacy' }, { target: 'Личный выбор важен, как и доступность общественных услуг (lichnyy vybor vazhen kak i dostupnost obshchestvennykh uslug)', english: 'personal choices matter, as does access to public services', title: 'considering environmental choices' }, { target: 'В отчёте видна тенденция, но не объяснены все причины (v otchyote vidna tendentsiya no ne obyasneny vse prichiny)', english: 'the report shows a trend but does not explain all causes', title: 'interpreting a report' }, { target: 'Стороны договорились проверить план в течение трёх месяцев (storony dogovorilis proverit plan v techeniye tryokh mesyatsev)', english: 'the parties agreed to test the plan for three months', title: 'negotiating an agreement' }, { target: 'Убедительная статья должна отличать факты от комментариев (ubeditelnaya statya dolzhna otlichat fakty ot kommentariyev)', english: 'persuasive reporting should distinguish facts from commentary', title: 'evaluating media' }, { target: 'Без своевременного обслуживания экономия сейчас увеличит будущие расходы (bez svoyevremennogo obsluzhivaniya ekonomiya seychas uvelichit budushchiye raskhody)', english: 'without timely maintenance, savings now will increase future costs', title: 'explaining consequences' },
      ],
      C1: [
        { target: 'Этот результат согласуется с гипотезой, но сам по себе не доказывает причинную связь (etot rezultat soglasuyetsya s gipotezoy no sam po sebe ne dokazyvayet prichinnuyu svyaz)', english: 'this result fits the hypothesis but does not by itself prove causation', title: 'qualifying a claim' }, { target: 'Каждое объяснение охватывает часть данных, однако имеет свои ограничения (kazhdoye obyasneniye okhvatyvayet chast dannykh odnako imeyet svoi ogranicheniya)', english: 'each explanation accounts for some data but has limitations', title: 'weighing competing evidence' },         { target: 'Просим разъяснить критерии, на основании которых было принято решение (prosim razyaznit kriterii na osnovanii kotorykh bylo prinyato resheniye)', english: 'please clarify the criteria on which the decision was based', title: 'writing formally' }, { target: 'Чёткая цель политики ещё не означает готовности к её реализации (chyotkaya tsel politiki yeshchyo ne oznachayet gotovnosti k yeyo realizatsii)', english: 'a clear policy goal does not mean it is ready to be implemented', title: 'examining implementation' }, { target: 'Размер выборки и период наблюдения ограничивают область применимости вывода (razmer vyborki i period nablyudeniya ogranichivayut oblast primenimosti vyvoda)', english: 'sample size and observation period limit the applicability of the conclusion', title: 'discussing research limits' }, { target: 'Одна и та же фраза может звучать по-разному в разных обстоятельствах (odna i ta zhe fraza mozhet zvuchat po-raznomu v raznykh obstoyatelstvakh)', english: 'the same phrase can sound different in different contexts', title: 'noticing register' }, { target: 'Институциональные меры работают лишь при последовательном исполнении (institutsionalnyye mery rabotayut lish pri posledovatelnom ispolnenii)', english: 'institutional measures work only when consistently implemented', title: 'analysing institutions' }, { target: 'Одновременное изменение двух показателей не доказывает причинной связи между ними (odnovremennoye izmeneniye dvukh pokazateley ne dokazyvayet prichinnoy svyazi mezhdu nimi)', english: 'two indicators changing together does not prove causation', title: 'separating cause and correlation' }, { target: 'Обобщая разные точки зрения, важно сохранить существенные разногласия (obobshchaya raznyye tochki zreniya vazhno sokhranit sushchestvennyye raznoglasiya)', english: 'a synthesis should preserve important disagreements', title: 'synthesizing viewpoints' }, { target: 'Иная формулировка проясняет спор, не скрывая его сути (inaya formulirovka proyasnyayet spor ne skryvaya yego suti)', english: 'a different framing clarifies a dispute without hiding its substance', title: 'reframing disagreement' },
      ],
      C2: [
        { target: 'Внешне он соглашается, однако его формулировка оставляет место для сомнений (vneshne on soglashayetsya odnako yego formulirovka ostavlyayet mesto dlya somneniy)', english: 'he appears to agree, yet his wording leaves room for doubt', title: 'reading implicit meaning' }, { target: 'При неполных данных особенно важно точно обозначать степень неопределённости (pri nepolnykh dannykh osobenno vazhno tochno oboznachat stepen neopredelyonnosti)', english: 'with incomplete data, it is especially important to state uncertainty precisely', title: 'communicating uncertainty' }, { target: 'Финал не разрешает неоднозначность, а переосмысливает начальный образ (final ne razreshayet neodnoznachnost a pereosmyslivayet nachalnyy obraz)', english: 'the ending does not resolve the ambiguity but reinterprets the opening image', title: 'interpreting literary ambiguity' },         { target: 'Признать этот довод не значит принять весь вывод (priznat etot dovod ne znachit prinyat ves vyvod)', english: 'acknowledging this argument does not mean accepting the whole conclusion', title: 'understanding a concession' }, { target: 'Без контекста выражение может показаться неуместным или резким (bez konteksta vyrazheniye mozhet pokazatsya neumestnym ili rezkim)', english: 'without context, an expression may seem inappropriate or blunt', title: 'adapting register' }, { target: 'Она выразила принципиальное возражение в предельно тактичной форме (ona vyrazila printsipialnoye vozrazheniye v predelno taktichnoy forme)', english: 'she voiced a fundamental objection in a tactful manner', title: 'interpreting subtle disagreement' }, { target: 'Точный синтез должен показать напряжение между противоречивыми свидетельствами (tochnyy sintez dolzhen pokazat napryazheniye mezhdu protivorechivymi svidetelstvami)', english: 'a precise synthesis should show tensions between conflicting evidence', title: 'synthesizing complex evidence' }, { target: 'Краткое выражение незаметно меняет исходную предпосылку (kratkoye vyrazheniye nezametno menyayet iskhodnuyu predposylku)', english: 'the concise expression subtly changes the original premise', title: 'recognizing idiomatic nuance' }, { target: 'Контрпример ослабляет общее утверждение, но не обязательно опровергает основную мысль (kontrprimer oslablyayet obshcheye utverzhdeniye no ne obyazatelno oprovergayet osnovnuyu mysl)', english: 'a counterexample weakens a general claim without necessarily refuting the core idea', title: 'evaluating a counterargument' }, { target: 'Это тонкое различие меняет представление о том, кто несёт ответственность (eto tonkoye razlichiye menyayet predstavleniye o tom kto nesyot otvetstvennost)', english: 'this fine distinction changes who is understood to be responsible', title: 'expressing a fine distinction' },
      ],
    },
    reading: {
      A1: 'Я каждый день изучаю русский язык дома. Я читаю новые слова и слушаю короткий разговор. Друг задаёт мне вопрос, и я отвечаю медленно. Сегодня я учу новые слова, а завтра повторяю их.',
      A2: 'На прошлой неделе я ездил с другом в соседний город. Сначала мы посмотрели карту, а потом нашли небольшое кафе рядом с вокзалом. Несмотря на дождь, мы посетили музей. По дороге домой я купил подарок для семьи.',
      B1: 'Жители района недавно начали обсуждать, как улучшить общественные места. Одни предложили поставить скамейки и посадить деревья, другие беспокоились о расходах на обслуживание. Мы собрали мнения и сравнили несколько вариантов. В конце участники решили провести пробный этап и изменить план с учётом результатов.',
      B2: 'Новый транспортный план предлагает увеличить число рейсов и улучшить связь между станциями. Сторонники считают, что это сократит время в пути и уменьшит зависимость от автомобилей. Однако для реализации нужны устойчивое финансирование и строительные работы, которые могут временно повлиять на движение. Поэтому оценка должна учитывать не только средние показатели, но и опыт разных районов.',
      C1: 'В отчёте отмечается, что участники стали чаще пользоваться услугой, однако это ещё не доказывает, что качество их жизни улучшилось. В выборку в основном вошли люди, уже знакомые с проектом, а период наблюдения был коротким. Для оценки долгосрочного эффекта потребуются участники из разных регионов, сопоставимые показатели и анализ других возможных причин изменений.',
      C2: 'Комиссия не отвергла необходимость реформы, а поставила под вопрос способность нынешнего плана выполнить обещанное. Некоторые данные действительно свидетельствуют о краткосрочном повышении эффективности, но оно распределилось неравномерно и, возможно, сопровождалось дополнительной нагрузкой на сотрудников. Если принять средние показатели за общую оценку успеха, существенные различия останутся незаметными. Более взвешенный вывод должен обозначить наблюдаемые преимущества, границы доказательств и нерешённые вопросы распределения.',
    },
    grammar: {
      A1: [{ title: 'Gender and basic sentence structure', summary: 'Build simple sentences and recognize grammatical gender.', explanation: 'Russian nouns have grammatical gender, and adjectives agree with the noun. A present-tense sentence usually has no word for “am/is/are.”', examples: ['Это новая книга. — This is a new book.', 'Анна студентка. — Anna is a student.'] }, { title: 'Personal pronouns and present tense', summary: 'Use subject pronouns and common present-tense verbs.', explanation: 'Verb endings mark person and number, so subject pronouns may be omitted when the subject is clear. Learn the stress and spelling of common forms.', examples: ['Я говорю по-русски. — I speak Russian.', 'Мы живём здесь. — We live here.'] }],
      A2: [{ title: 'Cases for basic meaning', summary: 'Recognize how noun endings show grammatical roles.', explanation: 'Russian case endings mark relations such as subject, direct object, possession, and location. Learn frequent phrases as chunks while noticing the ending.', examples: ['Я читаю книгу. — I am reading a book (accusative).', 'Книга на столе. — The book is on the table (prepositional).'] }, { title: 'Motion verbs and the past tense', summary: 'Talk about movement and completed past events.', explanation: 'Russian distinguishes common unidirectional and multidirectional motion verbs. Past-tense verbs agree with gender in the singular.', examples: ['Я иду домой. — I am going home (now).', 'Она ходила в музей. — She went to the museum.'] }],
      B1: [{ title: 'Aspect: completed and ongoing actions', summary: 'Choose perfective or imperfective verbs for context.', explanation: 'Imperfective verbs often present an action as ongoing, repeated, or process-focused. Perfective verbs often present it as completed or bounded.', examples: ['Я читал книгу. — I was reading the book.', 'Я прочитал книгу. — I finished reading the book.'] }, { title: 'Complex sentences and clauses', summary: 'Connect ideas with subordinate clauses and conjunctions.', explanation: 'Conjunctions such as потому что, хотя, and если express cause, concession, and condition. Keep the verb aspect and clause relation consistent.', examples: ['Я остался дома, потому что шёл дождь. — I stayed home because it was raining.', 'Если будет время, мы встретимся. — If there is time, we will meet.'] }],
      B2: [{ title: 'Participles and participial phrases', summary: 'Recognize compact descriptions in written Russian.', explanation: 'Participles combine verbal and adjectival properties. They agree with the noun and can make written descriptions more concise.', examples: ['студенты, изучающие язык — students who are studying the language', 'опубликованный отчёт — the published report'] }, { title: 'Passive and impersonal constructions', summary: 'Describe events without foregrounding an agent.', explanation: 'Russian can use passive participles and impersonal constructions to focus on an event or result rather than the person performing it.', examples: ['Решение было принято вчера. — The decision was made yesterday.', 'Здесь нельзя парковаться. — Parking is not allowed here.'] }],
      C1: [{ title: 'Formal connectors and argument structure', summary: 'Organize a formal argument and distinguish its logical steps.', explanation: 'Expressions such as тем не менее, кроме того, and следовательно signal contrast, addition, and inference. Make the relation between claims explicit.', examples: ['Тем не менее вывод требует проверки. — Nevertheless, the conclusion needs verification.', 'Следовательно, нужны дополнительные данные. — Consequently, more data are needed.'] }, { title: 'Attributing claims and evidence', summary: 'Report sources and qualify what evidence supports.', explanation: 'Use reporting verbs and source phrases to separate a study’s finding from an interpretation. Avoid implying causation from an association alone.', examples: ['Согласно отчёту, показатель вырос. — According to the report, the measure increased.', 'Эти данные сами по себе не подтверждают причинную связь. — These data alone do not confirm causation.'] }],
      C2: [{ title: 'Concession and argument scope', summary: 'Acknowledge a point while restricting its argumentative force.', explanation: 'Concessive phrases such as пусть даже and при всём уважении can recognize a limited point without adopting the broader conclusion.', examples: ['Даже если это так, вывод не следует автоматически. — Even if so, the conclusion does not follow automatically.', 'Признание этого факта не означает согласия с оценкой. — Acknowledging this fact does not mean agreeing with the assessment.'] }, { title: 'Register, implication, and precision', summary: 'Preserve pragmatic nuance and fine distinctions.', explanation: 'Word order, particles, and register can signal reservation or emphasis. Paraphrase only when the intended implication and degree of certainty remain intact.', examples: ['На первый взгляд это убедительно. — At first glance, this is convincing.', 'Точнее было бы сказать, что результат ограничен. — More precisely, the result is limited.'] }],
    },
  },
}

function buildPack(profile: LanguageProfile) {
  const grammarLessons: GrammarLesson[] = [
    ...levels.flatMap((level) => profile.grammar[level].map((topic, index) => ({
      id: `${profile.code}-grammar-${level.toLowerCase()}-${index + 1}`,
      level,
      title: topic.title,
      summary: topic.summary,
      sections: [{ heading: topic.title, explanation: topic.explanation, examples: topic.examples }],
      exercises: [{
        prompt: `Choose the example that demonstrates ${topic.title.toLocaleLowerCase()}.`,
        options: [...topic.examples, profile.phrases[level][index].target],
        answer: 0,
        explanation: topic.explanation,
      }],
    }))),
    ...buildCollegeGrammarLessons(profile.name),
  ]

  const supplementalLessons: SupplementalLesson[] = levels.flatMap((level) =>
    profile.phrases[level].map((phrase, index) => {
      const grammar = grammarLessons.find((lesson) => lesson.level === level)
      if (!grammar) throw new Error(`Missing ${level} grammar for ${profile.name}`)
      const questionOptions = [phrase.target, profile.phrases[level][(index + 1) % 10].target, profile.phrases[level][(index + 2) % 10].target]
      const answer = questionOptions.indexOf(phrase.target)
      return {
        id: `${profile.code}-course-${level.toLowerCase()}-${String(index + 1).padStart(2, '0')}`,
        level,
        title: `${phrase.title[0].toLocaleUpperCase()}${phrase.title.slice(1)}`,
        detail: `Learn a useful ${profile.name} expression for ${phrase.title}.`,
        minutes: `${lessonMinutes[level]} min`,
        objective: `Understand and use a ${level} expression for ${phrase.title}.`,
        vocabulary: [{ spanish: phrase.target, english: phrase.english }],
        grammarLessonId: grammar.id,
        grammarNote: profile.grammar[level][0].explanation,
        label: `${profile.name.toLocaleUpperCase()} · ${level} · ${phrase.title.toLocaleUpperCase()}`,
        passage: `${profile.script === 'Arab' ? phrase.target.replace(/\s*\([^)]*\)/g, '').trim() : phrase.target}\n\n${profile.reading[level]}\n\n${readingExtensions[profile.name][level]}`,
        questions: [
          { prompt: `Which ${profile.name} expression means “${phrase.english}”?`, options: questionOptions, answer },
          { prompt: 'Which level-appropriate reading develops this lesson?', options: ['The passage on the front of this lesson.', 'An unrelated list with no context.', 'No reading is provided.'], answer: 0 },
        ],
        speakingPrompt: `Say “${phrase.target}” aloud, then use it in a sentence about ${phrase.title}.`,
        listeningPrompt: `Listen for “${phrase.target}” and identify its meaning: ${phrase.english}.`,
      }
    }),
  )

  const starters: StarterLesson[] = profile.starter.map((item, index) => {
    const [target, english] = item.split('|')
    const readingPhrase = profile.script === 'Arab' ? target.replace(/\s*\([^)]*\)/g, '').trim() : target
    return {
      title: ['First greetings', 'Polite words', 'Say goodbye'][index],
      detail: `Start learning ${profile.name} with essential words and sound practice.`,
      minutes: `${8 + index * 2} min`,
      speakingPrompt: `Say ${target} aloud and practise using it in a short exchange.`,
      vocabulary: [{ spanish: target, english }],
      grammarFocus: 'First expressions',
      grammarExplanation: `Learn the complete expression ${target} as a useful phrase. Its meaning is “${english}.”`,
      passage: readingPhrase,
      questions: [{ prompt: `What does “${target}” mean?`, options: [english, 'please', 'good morning'], answer: 0 }],
      listeningPrompt: `Listen for ${target}, then repeat the expression.`,
    }
  })

  const assessmentQuestions: AssessmentQuestion[] = levels.flatMap((level) => profile.phrases[level].slice(0, 3).map((phrase) => {
    const wrongAnswers = profile.phrases[level].filter((candidate) => candidate !== phrase).slice(0, 3).map((candidate) => candidate.target)
    const answers = [phrase.target, ...wrongAnswers]
    return { prompt: `Choose the ${profile.name} expression for “${phrase.english}.”`, answers, correctIndex: 0 }
  }))

  const activityCards: PracticeActivity[] = levels.flatMap((level) => profile.phrases[level].slice(0, 2).map((phrase, index) => ({
    level,
    icon: index === 0 ? '♫' : '◉',
    title: index === 0 ? 'Listen and recognize' : 'Choose the useful phrase',
    prompt: `Which ${profile.name} phrase means “${phrase.english}”?`,
    audioPhrase: phrase.target,
    options: [phrase.target, ...profile.phrases[level].slice(4, 6).map((entry) => entry.target)],
    answer: 0,
  })))

  const resources: Resource[] = levels.map((level) => {
    const sample = profile.phrases[level][0]
    return {
      type: 'video',
      title: `${level} ${profile.name} listening practice`,
      description: `Browse level-matched ${profile.name} videos and practise with the companion reading.`,
      source: 'YouTube video search',
      level,
      tag: `Video practice · ${level}`,
      url: `https://www.youtube.com/results?search_query=${encodeURIComponent(`${profile.name} ${level} comprehensible input listening`)}`,
      embedUrl: '',
      passage: `${profile.reading[level]}\n\n${readingExtensions[profile.name][level]}`,
      comprehension: [{
        prompt: `Which expression means “${sample.english}”?`,
        answers: [sample.target, profile.phrases[level][1].target, profile.phrases[level][2].target],
        correctIndex: 0,
      }],
    }
  })

  const dlptResources: Resource[] = levels.map((level) => ({
    type: 'reading',
    title: `${level} DLPT-style reading · ${profile.name}`,
    description: `Read a longer ${profile.name} passage, then answer main-idea, detail, inference, and purpose questions.`,
    source: 'DLPT-style practice',
    level,
    tag: `ILR reference ${level}`,
    url: '',
    embedUrl: '',
    passage: `${profile.reading[level]}\n\n${readingExtensions[profile.name][level]}`,
    comprehension: dlptQuestions[level].map((question, questionIndex) => {
      const offset = (levels.indexOf(level) + questionIndex) % question.answers.length
      return {
        ...question,
        answers: [...question.answers.slice(offset), ...question.answers.slice(0, offset)],
        correctIndex: (question.correctIndex - offset + question.answers.length) % question.answers.length,
      }
    }),
  }))

  const lessonContent = Object.fromEntries(supplementalLessons.map((lesson) => [lesson.title, {
    label: lesson.label,
    text: lesson.passage,
    questions: lesson.questions,
  }]))
  for (const starter of starters) {
    lessonContent[starter.title] = {
      label: `FIRST WORDS · ${profile.name.toLocaleUpperCase()}`,
      text: starter.passage,
      questions: starter.questions,
    }
  }
  const lessonSupport = Object.fromEntries(supplementalLessons.map((lesson) => [lesson.title, {
    objective: lesson.objective,
    vocabulary: lesson.vocabulary,
    grammarLessonId: lesson.grammarLessonId,
    grammarNote: lesson.grammarNote,
    speakingPrompt: lesson.speakingPrompt,
    listeningPrompt: lesson.listeningPrompt,
  }]))

  return {
    name: profile.name,
    code: profile.code,
    script: profile.script,
    grammarLessons,
    grammarLevels: levels,
    courseLevels: ['Pre-A1', ...levels] as const,
    starters,
    supplementalLessons,
    lessonContent,
    lessonSupport,
    assessmentQuestions,
    activityCards,
    resources: [...resources, ...dlptResources],
  }
}

export const additionalLanguagePacks = {
  'Mandarin Chinese': buildPack(profiles['Mandarin Chinese']),
  'Modern Standard Arabic': buildPack(profiles['Modern Standard Arabic']),
  Russian: buildPack(profiles.Russian),
}

export type LearningLanguage = 'Spanish' | 'Italian' | AddedLanguage
export const learningLanguages: LearningLanguage[] = [
  'Spanish',
  'Italian',
  'Mandarin Chinese',
  'Modern Standard Arabic',
  'Russian',
]

export function isLearningLanguage(value: string): value is LearningLanguage {
  return learningLanguages.some((language) => language === value)
}

export function getLanguageTextMetadata(language: string) {
  if (language === 'Mandarin Chinese') return { lang: 'zh-CN', dir: 'auto' as const }
  if (language === 'Modern Standard Arabic') return { lang: 'ar', dir: 'rtl' as const }
  if (language === 'Russian') return { lang: 'ru-RU', dir: 'auto' as const }
  if (language === 'Italian') return { lang: 'it-IT', dir: 'auto' as const }
  return { lang: 'es-ES', dir: 'auto' as const }
}
